// Wamp/Skinning/ClassicSprites/ClassicPixelSheets.swift
// GENERATED pixel maps extracted 1:1 from base-2.91 sprite sheets
// (scripts in the session scratchpad; re-extract from skins/base-2.91.wsz).
// Baked text and LED art are not worth re-deriving as vector structure —
// exact pixel maps drawn as 1-pt rects stay crisp at every backing scale.

import AppKit

enum ClassicPixelSheets {
    static let shuffleOff = [
        "!!##$###%%%%&''''(())**++,,--../001123345667778",
        "9::::::::::::::::::::::::::::::::::::::::::::;8",
        "9:<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<:=8",
        ">:<????????????????????????????????????????:@A8",
        ">:<??AAAAA?????????????????????????????????:@A8",
        ">:<??ABBBC??DDD?D??D?D??D?DDD?DDD?D???DDD??:@A8",
        ">:<??ABBBC??D???D??D?D??D?D???D???D???D????:@A8",
        "E:<??ACCCC??DDD?DDDD?D??D?DDD?DDD?D???DDD??:@A8",
        "E:<???????????D?D??D?D??D?D???D???D???D????:@A8",
        ">:<?????????DDD?D??D??DD??D???D???DDD?DDD??:@A8",
        "E:<????????????????????????????????????????:@A8",
        ">:<:::::::::::::::::::::::::::::::::::::::::@A8",
        ">::;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@A8",
        ">;=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8",
        ">>EEFGHFFFFIFIIJJJKKKLM!!#######%&&&&'''()))**8",
    ]

    static let shuffleOffPressed = [
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
        "NNOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPOQNN",
        "NNPRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRPNN",
        "NNPRPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPNN",
        "NNPRPPNNNNNPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPNN",
        "NNPRPPNBBBSPPTTTPTPPTPTPPTPTTTPTTTPTPPPTTTPPPNN",
        "NNPRPPNBBBSPPTPPPTPPTPTPPTPTPPPTPPPTPPPTPPPPPNN",
        "NNPRPPNSSSSPPTTTPTTTTPTPPTPTTTPTTTPTPPPTTTPPPNN",
        "NNPRPPPPPPPPPPPTPTPPTPTPPTPTPPPTPPPTPPPTPPPPPNN",
        "NNPRPPPPPPPPPTTTPTPPTPPTTPPTPPPTPPPTTTPTTTPPPNN",
        "NNPRPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPNN",
        "NNPRPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPNN",
        "NNORPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPNN",
        "NNQNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    ]

    static let shuffleOn = [
        "!!##$###%%%%&''''(())**++,,--../001123345667778",
        "9::::::::::::::::::::::::::::::::::::::::::::;8",
        "9:<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<:=8",
        ">:<????????????????????????????????????????:@A8",
        ">:<??AAAAA?????????????????????????????????:@A8",
        ">:<??AUUUC??DDD?D??D?D??D?DDD?DDD?D???DDD??:@A8",
        ">:<??AUUUC??D???D??D?D??D?D???D???D???D????:@A8",
        "E:<??ACCCC??DDD?DDDD?D??D?DDD?DDD?D???DDD??:@A8",
        "E:<???????????D?D??D?D??D?D???D???D???D????:@A8",
        ">:<?????????DDD?D??D??DD??D???D???DDD?DDD??:@A8",
        "E:<????????????????????????????????????????:@A8",
        ">:<:::::::::::::::::::::::::::::::::::::::::@A8",
        ">::;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@A8",
        ">;=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8",
        ">>EEFGHFFFFIFIIJJJKKKLM!!#######%&&&&'''()))**8",
    ]

    static let shuffleOnPressed = [
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
        "NNOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPOQNN",
        "NNPRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRPNN",
        "NNPRPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPNN",
        "NNPRPPNNNNNPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPNN",
        "NNPRPPNUUUSPPTTTPTPPTPTPPTPTTTPTTTPTPPPTTTPPPNN",
        "NNPRPPNUUUSPPTPPPTPPTPTPPTPTPPPTPPPTPPPTPPPPPNN",
        "NNPRPPNSSSSPPTTTPTTTTPTPPTPTTTPTTTPTPPPTTTPPPNN",
        "NNPRPPPPPPPPPPPTPTPPTPTPPTPTPPPTPPPTPPPTPPPPPNN",
        "NNPRPPPPPPPPPTTTPTPPTPPTTPPTPPPTPPPTTTPTTTPPPNN",
        "NNPRPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPNN",
        "NNPRPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPNN",
        "NNORPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPNN",
        "NNQNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    ]

    static let repeatOff = [
        ">>>>>>EEEVHFHFFFFFIJIIWKWWMM",
        "(::::::::::::::::::::::::::;",
        "):<<<<<<<<<<<<<<<<<<<<<<<<:=",
        "):<??????????????????????:@A",
        "):<??AAAAA???????????????:@A",
        "):<??ABBBC??:ADDDDDD?????:@A",
        "):<??ABBBC??;???????D????:@A",
        "*:<??ACCCC??DDD?????D????:@A",
        "):<?????????DD??????D????:@A",
        "*:<?????????D?DDDDDD?????:@A",
        "):<??????????????????????:@A",
        "*:<:::::::::::::::::::::::@A",
        "*::;@@@@@@@@@@@@@@@@@@@@@@@A",
        "*;=AAAAAAAAAAAAAAAAAAAAAAAAA",
        "+,,-,.../01122383455X77YZ[[[",
    ]

    static let repeatOffPressed = [
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNN",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNN",
        "NNOPPPPPPPPPPPPPPPPPPPPPPOQN",
        "NNPRRRRRRRRRRRRRRRRRRRRRRRPN",
        "NNPRPPPPPPPPPPPPPPPPPPPPPPPN",
        "NNPRPPNNNNNPPPPPPPPPPPPPPPPN",
        "NNPRPPNBBBSPPOQNNNNNNPPPPPPN",
        "NNPRPPNBBBSPPQPPPPPPPNPPPPPN",
        "NNPRPPNSSSSPPNNNPPPPPNPPPPPN",
        "NNPRPPPPPPPPPNNPPPPPPNPPPPPN",
        "NNPRPPPPPPPPPNPNNNNNNPPPPPPN",
        "NNPRPPPPPPPPPPPPPPPPPPPPPPPN",
        "NNPRPPPPPPPPPPPPPPPPPPPPPPPN",
        "NNORPPPPPPPPPPPPPPPPPPPPPPPN",
        "NNQNNNNNNNNNNNNNNNNNNNNNNNNN",
    ]

    static let repeatOn = [
        ">>>>>>EEEVHFHFFFFFIJIIWKWWMM",
        "(::::::::::::::::::::::::::;",
        "):<<<<<<<<<<<<<<<<<<<<<<<<:=",
        "):<??????????????????????:@A",
        "):<??AAAAA???????????????:@A",
        "):<??AUUUC??:ADDDDDD?????:@A",
        "):<??AUUUC??;???????D????:@A",
        "*:<??ACCCC??DDD?????D????:@A",
        "):<?????????DD??????D????:@A",
        "*:<?????????D?DDDDDD?????:@A",
        "):<??????????????????????:@A",
        "*:<:::::::::::::::::::::::@A",
        "*::;@@@@@@@@@@@@@@@@@@@@@@@A",
        "*;=AAAAAAAAAAAAAAAAAAAAAAAAA",
        "+,,-,.../01122383455X77YZ[[[",
    ]

    static let repeatOnPressed = [
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNN",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNN",
        "NNOPPPPPPPPPPPPPPPPPPPPPPOQN",
        "NNPRRRRRRRRRRRRRRRRRRRRRRRPN",
        "NNPRPPPPPPPPPPPPPPPPPPPPPPPN",
        "NNPRPPNNNNNPPPPPPPPPPPPPPPPN",
        "NNPRPPNUUUSPPOQNNNNNNPPPPPPN",
        "NNPRPPNUUUSPPQPPPPPPPNPPPPPN",
        "NNPRPPNSSSSPPNNNPPPPPNPPPPPN",
        "NNPRPPPPPPPPPNNPPPPPPNPPPPPN",
        "NNPRPPPPPPPPPNPNNNNNNPPPPPPN",
        "NNPRPPPPPPPPPPPPPPPPPPPPPPPN",
        "NNPRPPPPPPPPPPPPPPPPPPPPPPPN",
        "NNORPPPPPPPPPPPPPPPPPPPPPPPN",
        "NNQNNNNNNNNNNNNNNNNNNNNNNNNN",
    ]

    static let eqOff = [
        ":::::::::::::::::::::;]",
        ":<<<<<<<<<<<<<<<<<<<:=8",
        ":<?????????????????:@A3",
        ":<??AAAA???DD??DD??:@A^",
        ":<??ABBC??D???D??D?:@A8",
        ":<??ABBC??DDD?D??D?:@A8",
        ":<??ACCC??D???D?D??:@A8",
        ":<?????????DD??D?D?:@A5",
        ":<::::::::::::::::::@A5",
        "::;@@@@@@@@@@@@@@@@@@A6",
        ";=AAAAAAAAAAAAAAAAAAAA6",
        "()**,,,,.-../0112238846",
    ]

    static let eqOffPressed = [
        "NNNNNNNNNNNNNNNNNNNNNNN",
        "NNNNNNNNNNNNNNNNNNNNNNN",
        "NTOPPPPPPPPPPPPPPPPPPQN",
        "NTPRRRRRRRRRRRRRRRRRRPN",
        "NTPRPPPPPPPPPPPPPPPPPPN",
        "NTPRPPNNNNPPPTTPPTTPPPN",
        "NTPRPPNBBSPPTPPPTPPTPPN",
        "NTPRPPNBBSPPTTTPTPPTPPN",
        "NTPRPPNSSSPPTPPPTPTPPPN",
        "NTPRPPPPPPPPPTTPPTPTPPN",
        "NTORPPPPPPPPPPPPPPPPPPN",
        "NTQNNNNNNNNNNNNNNNNNNNN",
    ]

    static let eqOn = [
        ":::::::::::::::::::::;8",
        ":<<<<<<<<<<<<<<<<<<<:=8",
        ":<?????????????????:@A8",
        ":<??AAAA???DD??DD??:@A8",
        ":<??AUUC??D???D??D?:@A8",
        ":<??AUUC??DDD?D??D?:@A8",
        ":<??ACCC??D???D?D??:@A8",
        ":<?????????DD??D?D?:@A8",
        ":<::::::::::::::::::@A8",
        "::;@@@@@@@@@@@@@@@@@@A8",
        ";=AAAAAAAAAAAAAAAAAAAA8",
        "88888888888888888888888",
    ]

    static let eqOnPressed = [
        "NTNNNNNNNNNNNNNNNNNNNNN",
        "NTNNNNNNNNNNNNNNNNNNNNN",
        "NTOPPPPPPPPPPPPPPPPPPQN",
        "NTPRRRRRRRRRRRRRRRRRRPN",
        "NTPRPPPPPPPPPPPPPPPPPPN",
        "NTPRPPNNNNPPPTTPPTTPPPN",
        "NTPRPPNUUSPPTPPPTPPTPPN",
        "NTPRPPNUUSPPTTTPTPPTPPN",
        "NTPRPPNSSSPPTPPPTPTPPPN",
        "NTPRPPPPPPPPPTTPPTPTPPN",
        "NTORPPPPPPPPPPPPPPPPPPN",
        "NTNNNNNNNNNNNNNNNNNNNNN",
    ]

    static let plOff = [
        ":::::::::::::::::::::;_",
        ":<<<<<<<<<<<<<<<<<<<:=_",
        ":<?????????????????:@A`",
        ":<??AAAA??DDD?D????:@A_",
        ":<??ABBC??D?D?D????:@A`",
        ":<??ABBC??DDD?D????:@Aa",
        ":<??ACCC??D???D????:@Aa",
        ":<????????D???DDD??:@Aa",
        ":<::::::::::::::::::@Aa",
        "::;@@@@@@@@@@@@@@@@@@Aa",
        ";=AAAAAAAAAAAAAAAAAAAAb",
        "667YYZ[[cdefghhh```_aaa",
    ]

    static let plOffPressed = [
        "NNNNNNNNNNNNNNNNNNNNNNN",
        "NNNNNNNNNNNNNNNNNNNNNNN",
        "TNOPPPPPPPPPPPPPPPPPOQN",
        "TNPRRRRRRRRRRRRRRRRRRPN",
        "TNPRPPPPPPPPPPPPPPPPPPN",
        "TNPRPPNNNNPPTTTPTPPPPPN",
        "TNPRPPNBBSPPTPTPTPPPPPN",
        "TNPRPPNBBSPPTTTPTPPPPPN",
        "TNPRPPNSSSPPTPPPTPPPPPN",
        "TNPRPPPPPPPPTPPPTTTPPPN",
        "TNORPPPPPPPPPPPPPPPPPPN",
        "TNQNNNNNNNNNNNNNNNNNNNN",
    ]

    static let plOn = [
        ":::::::::::::::::::::;8",
        ":<<<<<<<<<<<<<<<<<<<:=8",
        ":<?????????????????:@A8",
        ":<??AAAA??DDD?D????:@A8",
        ":<??AUUC??D?D?D????:@A8",
        ":<??AUUC??DDD?D????:@A8",
        ":<??ACCC??D???D????:@A8",
        ":<????????D???DDD??:@A8",
        ":<::::::::::::::::::@A8",
        "::;@@@@@@@@@@@@@@@@@@A8",
        ";=AAAAAAAAAAAAAAAAAAAA8",
        "88888888888888888888888",
    ]

    static let plOnPressed = [
        "TNNNNNNNNNNNNNNNNNNNNNN",
        "TNNNNNNNNNNNNNNNNNNNNNN",
        "TNOPPPPPPPPPPPPPPPPPOQN",
        "TNPRRRRRRRRRRRRRRRRRRPN",
        "TNPRPPPPPPPPPPPPPPPPPPN",
        "TNPRPPNNNNPPTTTPTPPPPPN",
        "TNPRPPNUUSPPTPTPTPPPPPN",
        "TNPRPPNUUSPPTTTPTPPPPPN",
        "TNPRPPNSSSPPTPPPTPPPPPN",
        "TNPRPPPPPPPPTPPPTTTPPPN",
        "TNORPPPPPPPPPPPPPPPPPPN",
        "TNQNNNNNNNNNNNNNNNNNNNN",
    ]

    static let stereoOn = [
        ".ijklllmmnnopqprrrssstttuufhh",
        "vwxyz{|}}~~~{ÀÀÀÁÁÂÂÂÃÄÅÆÇÈh`",
        "wÉz|ÊËÌÍÎÍÏÏÐÑÐÒÒÒÓÔÔÕÖ××ÅÇÈh",
        "ØzÙËÎÚÛÜÝÞÞÞßàßßááââãääåÖæçÇh",
        "y|ËèéêëìÝíîïïÜííêðñòóôõöäÖ÷øù",
        "úÙÌéûüëýÝþÿĀòāĂĂăÝĄāéÝèąöĆæćĈ",
        "yÙÌèĉĊïýÝþċòĄòĂĄîÝĄăòÝèąöĆ÷ćĈ",
        "y|ËðČĊĉóċíüāāĉñĉčíāāðíČČĎĆ÷ćù",
        "lz}ÌÎÚďďĐàĐÞßßááââââããäåĆæçÇù",
        "kyz|ÊđĒÑÐÑÐÏÏÐÓÓÔÔÔÔÔÔĆÖæçøĈē",
        "kklmz{{{ÀÀÀÀÁÁÁÂÂÂÂ×××÷ÄćÇĈùē",
        "jkĔĕĕĖĖppppprrsssssÆÆÆÇÈÈù``ē",
    ]

    static let stereoOff = [
        ".//ėėė22388Ę557XYZZ[[cęcffhhh",
        "Ěi/ė222388ĘĘĘ57YYZ[[[cęcfffh`",
        "i//ėė23383Ę5557ZZZ[[ccffffhhh",
        "Ě//ėė22ěĜ8Ę556XYZZ[cęcęfffhhh",
        "/ė/ĝĞğĝĠĜġĝĢĢĝġġĢģĤĥĦģĤħĦfĨĨ`",
        "i/ėĩĩĪīěĜĘĬĢĥĭĤĤġĮįĭĢĮĦİħhhh`",
        "/ėėīįĬğěĜĘıĥįĥĤįĝĮįĲħĮfĳĴhĨh`",
        "/ėėĳĭĬįīıġĪĭĭįĤįZġĭĭģİĭĭīhĨ``",
        "ėė2ė2288Ę557YXZZZ[[ffffhhhĨ``",
        "Ěėė2283ĘĘ5567XZZ[ccęfffhhhĨĨē",
        "ėė22388ĘĘ57XYZZZ[[ccffhhhh`ēē",
        "/ė2283855577ZZ[[[[cfffhhh```ē",
    ]

    static let monoOn = [
        "$ĵĶ$ĶĶķĸĸĸĸĹĹĹĺĺĺĺĻĻĻļļĽ*ľ,",
        "$$ĶĶĸĿŀŁłłŃŁŃŃŃńńńŃŃŅņŇňŉŊŋ",
        "$$ĶķŀŌōŎŎŏŎŐŐŐŏŏŏőŏőőŒœŔŇňŊ",
        "ĵ$ķĿŌŎŕŖŗŗŗŘŘŘŘřřřřřŚśŜőŔŇŝ",
        "$ĵŞŁŎóÝòşìÝŠšŢŢţŤÿāāťŢŢĉŦŔň",
        "$ĶĿłŎóÝŧÝŠŨũŪŤþÝŪĂŠÝŪŤŧÝèŔň",
        "ĵĶĿŁŎóÝŧÝŠŨũìţþÝìĂŠÝìĄčÝÞŔň",
        "$$ķŁōčïřĀšĄýčăŨýüĄšŨčăéÜŦÙň",
        "$$ĸĿłōŏŕŖŖŖŖŖŖŖūūśśŬŬŜŜŦŔŇŝ",
        "$$ĶķŞŁłłŭŭŭŭŭŭŭŭŒŒŮŮŮœŔŅňŝů",
        "$$$ŰĸĸŞŞűűűűűűűņņņņŇŇŇňŉŝwŋ",
        "$$#ŰŰŰŲųųųŴŵŵŵŵļļĽĽŊŶŶŋŋŋvi",
    ]

    static let monoOff = [
        "$ĵ$$$#$##%%&&&''ŷ(******+,,",
        "$$$$#$###%&&&''ŷ((((*ľ+,,,Ÿ",
        "$$$$###%&&&&''''(*(****+,,,",
        "ĵ$$$$$#%%&&&&''(((***++,,,Ÿ",
        "$$$$ŰŹźŻżĴźĪěŽŽžſƀŽŽěŽŽž,,,",
        "$$$#ŰŹź%źŹƁſŻſ(źŻƁƂƃŻſ,ƃě,Ÿ",
        "ĵ$$##Źź%źŹƁſĴžīźĴƁƂƃĠžƄƃīŸŸ",
        "$$#Ű$ěƁ%ƁěžƅīĴƁĪƅžěƁƄĠƁŹ,ŸŸ",
        "$$Ű$Ű#%%&&&'(''((**ľľ,,Ÿ,ŸŸ",
        "$$#$%#%&&&Ɔ''(((***+ľ,,,ŸŸĚ",
        "$$####%%&'Ɔ'((((***,,,,,ŸŸŸ",
        "$$##%%%&'&'((((((**,,,,,ŸĚi",
    ]

    static let btnPrevious = [
        ":::::::::::::::::::::;b",
        ":<<<<<<<<<<<<<<<<<<<:=a",
        ":<?????????????????:;A_",
        ":<?????????????????:;A_",
        ":<????AAA?????AA???:@Aa",
        ":<????AƇ<????AƇ<???:@A_",
        ":<????AƇ<???AƇƇ<???:@A_",
        ":<????AƇ<??AƇƇƇ<???:@A`",
        ":<????AƇ<?AƇƇƇƇ<???:@A_",
        ":<????AƇ<?<ƇƇƇƇ<???:@A`",
        ":<????AƇ<??<ƇƇƇ<???:@A`",
        ":<????AƇ<???<ƇƇ<???:@A`",
        ":<????AƇ<????<Ƈ<???:@A`",
        ":<????<<<?????<<???:@A`",
        ":<::::::::::::::::::@A`",
        "::;@@@@@@@@@@@@@@@@@@AĨ",
        ";=AAAAAAAAAAAAAAAAAAAAh",
        "ƈƉƉƉƉƉƊƋƌƍƎƎƎabaa___`hĨ",
    ]

    static let btnPreviousPressed = [
        "NNNNNNNNNNNNNNNNNNNNNNN",
        "NNNNNNNNNNNNNNNNNNNNNNN",
        "NNOPPPPPPPPPPPPPPPPPOQN",
        "NNPRRRRRRRRRRRRRRRRRRPN",
        "NNPRPPPPPPPPPPPPPPPPPPN",
        "NNPRPPPPPPPPPPPPPPPPPPN",
        "NNPRPPPPNNNPPPPPNNPPPPN",
        "NNPRPPPPNARPPPPNARPPPPN",
        "NNPRPPPPNARPPPNAARPPPPN",
        "NNPRPPPPNARPPNAAARPPPPN",
        "NNPRPPPPNARPNAAAARPPPPN",
        "NNPRPPPPNARPRAAAARPPPPN",
        "NNPRPPPPNARPPRAAARPPPPN",
        "NNPRPPPPNARPPPRAARPPPPN",
        "NNPRPPPPNARPPPPRARPPPPN",
        "NNPRPPPPRRRPPPPPRRPPPPN",
        "NNORPPPPPPPPPPPPPPPPPPN",
        "NNQNNNNNNNNNNNNNNNNNNNN",
    ]

    static let btnPlay = [
        ":::::::::::::::::::::;6",
        ":<<<<<<<<<<<<<<<<<<<:=6",
        ":<?????????????????:;A4",
        ":<?????????????????:;A4",
        ":<????AA???????????:@A5",
        ":<????AƇAA?????????:@A4",
        ":<????AƇƇƇAA???????:@A5",
        ":<????AƇƇƇƇƇAA?????:@A4",
        ":<????AƇƇƇƇƇƇƇAA???:@A4",
        ":<????AƇƇƇƇƇƇƇ<<???:@A8",
        ":<????AƇƇƇƇƇ<<?????:@A4",
        ":<????AƇƇƇ<<???????:@A3",
        ":<????AƇ<<?????????:@A3",
        ":<????<<???????????:@A8",
        ":<::::::::::::::::::@A8",
        "::;@@@@@@@@@@@@@@@@@@A3",
        ";=AAAAAAAAAAAAAAAAAAAA8",
        "Ĩgfffdcc[[ZZYY666448^^]",
    ]

    static let btnPlayPressed = [
        "NNNNNNNNNNNNNNNNNNNNNNN",
        "NNNNNNNNNNNNNNNNNNNNNNN",
        "NNOPPPPPPPPPPPPPPPPPOQN",
        "NNPRRRRRRRRRRRRRRRRRRPN",
        "NNPRPPPPPPPPPPPPPPPPPPN",
        "NNPRPPPPPPPPPPPPPPPPPPN",
        "NNPRPPPPNNPPPPPPPPPPPPN",
        "NNPRPPPPNANNPPPPPPPPPPN",
        "NNPRPPPPNAAANNPPPPPPPPN",
        "NNPRPPPPNAAAAANNPPPPPPN",
        "NNPRPPPPNAAAAAAANNPPPPN",
        "NNPRPPPPNAAAAAAARRPPPPN",
        "NNPRPPPPNAAAAARRPPPPPPN",
        "NNPRPPPPNAAARRPPPPPPPPN",
        "NNPRPPPPNARRPPPPPPPPPPN",
        "NNPRPPPPRRPPPPPPPPPPPPN",
        "NNORPPPPPPPPPPPPPPPPPPN",
        "NNQNNNNNNNNNNNNNNNNNNNN",
    ]

    static let btnPause = [
        ":::::::::::::::::::::;*",
        ":<<<<<<<<<<<<<<<<<<<:=)",
        ":<?????????????????:;A(",
        ":<?????????????????:;A(",
        ":<???AAAA???AAAA???:@A)",
        ":<???AƇƇ<???AƇƇ<???:@A(",
        ":<???AƇƇ<???AƇƇ<???:@A(",
        ":<???AƇƇ<???AƇƇ<???:@A(",
        ":<???AƇƇ<???AƇƇ<???:@A)",
        ":<???AƇƇ<???AƇƇ<???:@A(",
        ":<???AƇƇ<???AƇƇ<???:@A(",
        ":<???AƇƇ<???AƇƇ<???:@A(",
        ":<???AƇƇ<???AƇƇ<???:@Aŷ",
        ":<???<<<<???<<<<???:@A(",
        ":<::::::::::::::::::@A'",
        "::;@@@@@@@@@@@@@@@@@@A(",
        ";=AAAAAAAAAAAAAAAAAAAA'",
        "21000v..-,-,+++ľ))(((''",
    ]

    static let btnPausePressed = [
        "NNNNNNNNNNNNNNNNNNNNNNN",
        "NNNNNNNNNNNNNNNNNNNNNNN",
        "NNOPPPPPPPPPPPPPPPPPOQN",
        "NNPRRRRRRRRRRRRRRRRRRPN",
        "NNPRPPPPPPPPPPPPPPPPPPN",
        "NNPRPPPPPPPPPPPPPPPPPPN",
        "NNPRPPPNNNNPPPNNNNPPPPN",
        "NNPRPPPNAARPPPNAARPPPPN",
        "NNPRPPPNAARPPPNAARPPPPN",
        "NNPRPPPNAARPPPNAARPPPPN",
        "NNPRPPPNAARPPPNAARPPPPN",
        "NNPRPPPNAARPPPNAARPPPPN",
        "NNPRPPPNAARPPPNAARPPPPN",
        "NNPRPPPNAARPPPNAARPPPPN",
        "NNPRPPPNAARPPPNAARPPPPN",
        "NNPRPPPRRRRPPPRRRRPPPPN",
        "NNORPPPPPPPPPPPPPPPPPPN",
        "NNQNNNNNNNNNNNNNNNNNNNN",
    ]

    static let btnStop = [
        ":::::::::::::::::::::;L",
        ":<<<<<<<<<<<<<<<<<<<:=L",
        ":<?????????????????:;AM",
        ":<?????????????????:;AM",
        ":<????AAAAAAAAAA???:@AM",
        ":<????AƇƇƇƇƇƇƇƇ<???:@AM",
        ":<????AƇƇƇƇƇƇƇƇ<???:@AK",
        ":<????AƇƇƇƇƇƇƇƇ<???:@AL",
        ":<????AƇƇƇƇƇƇƇƇ<???:@AL",
        ":<????AƇƇƇƇƇƇƇƇ<???:@AW",
        ":<????AƇƇƇƇƇƇƇƇ<???:@AK",
        ":<????AƇƇƇƇƇƇƇƇ<???:@AL",
        ":<????AƇƇƇƇƇƇƇƇ<???:@AW",
        ":<????<<<<<<<<<<???:@AW",
        ":<::::::::::::::::::@AW",
        "::;@@@@@@@@@@@@@@@@@@AK",
        ";=AAAAAAAAAAAAAAAAAAAAJ",
        "'&&&&%##Ű$##!#!!LMLKKWJ",
    ]

    static let btnStopPressed = [
        "NNNNNNNNNNNNNNNNNNNNNNN",
        "NNNNNNNNNNNNNNNNNNNNNNN",
        "NNOPPPPPPPPPPPPPPPPPOQN",
        "NNPRRRRRRRRRRRRRRRRRRPN",
        "NNPRPPPPPPPPPPPPPPPPPPN",
        "NNPRPPPPPPPPPPPPPPPPPPN",
        "NNPRPPPPNNNNNNNNNNPPPPN",
        "NNPRPPPPNAAAAAAAARPPPPN",
        "NNPRPPPPNAAAAAAAARPPPPN",
        "NNPRPPPPNAAAAAAAARPPPPN",
        "NNPRPPPPNAAAAAAAARPPPPN",
        "NNPRPPPPNAAAAAAAARPPPPN",
        "NNPRPPPPNAAAAAAAARPPPPN",
        "NNPRPPPPNAAAAAAAARPPPPN",
        "NNPRPPPPNAAAAAAAARPPPPN",
        "NNPRPPPPRRRRRRRRRRPPPPN",
        "NNORPPPPPPPPPPPPPPPPPPN",
        "NNQNNNNNNNNNNNNNNNNNNNN",
    ]

    static let btnNext = [
        ":::::::::::::::::::::;:",
        ":<<<<<<<<<<<<<<<<<<<:=:",
        ":<?????????????????:;A:",
        ":<?????????????????:;A:",
        ":<????AA?????AAA???:@A:",
        ":<????AƇA????AƇ<???:@A:",
        ":<????AƇƇA???AƇ<???:@A:",
        ":<????AƇƇƇA??AƇ<???:@A:",
        ":<????AƇƇƇƇA?AƇ<???:@A:",
        ":<????AƇƇƇƇ<?AƇ<???:@A:",
        ":<????AƇƇƇ<??AƇ<???:@A:",
        ":<????AƇƇ<???AƇ<???:@A:",
        ":<????AƇ<????AƇ<???:@A:",
        ":<????<<?????<<<???:@A:",
        ":<::::::::::::::::::@A:",
        "::;@@@@@@@@@@@@@@@@@@AƏ",
        ";=AAAAAAAAAAAAAAAAAAAAN",
        "JJFIFFFFFFEEEEEE>>>>>>N",
    ]

    static let btnNextPressed = [
        "NNNNNNNNNNNNNNNNNNNNNN",
        "NNNNNNNNNNNNNNNNNNNNNN",
        "NNOPPPPPPPPPPPPPPPPOQN",
        "NNPRRRRRRRRRRRRRRRRRPN",
        "NNPRPPPPPPPPPPPPPPPPPN",
        "NNPRPPPPPPPPPPPPPPPPPN",
        "NNPRPPPPNNPPPPPNNNPPPN",
        "NNPRPPPPNANPPPPNARPPPN",
        "NNPRPPPPNAANPPPNARPPPN",
        "NNPRPPPPNAAANPPNARPPPN",
        "NNPRPPPPNAAAANPNARPPPN",
        "NNPRPPPPNAAAARPNARPPPN",
        "NNPRPPPPNAAARPPNARPPPN",
        "NNPRPPPPNAARPPPNARPPPN",
        "NNPRPPPPNARPPPPNARPPPN",
        "NNPRPPPPRRPPPPPRRRPPPN",
        "NNORPPPPPPPPPPPPPPPPPN",
        "NNQNNNNNNNNNNNNNNNNNNN",
    ]

    static let btnEject = [
        ":::::::::::::::::::::;",
        ":<<<<<<<<<<<<<<<<<<<:=",
        ":<?????????????????:@A",
        ":<????????A????????:@A",
        ":<???????AƇA???????:@A",
        ":<??????AƇƇƇA??????:@A",
        ":<?????AƇƇƇƇƇA?????:@A",
        ":<????AƇƇƇƇƇƇƇA????:@A",
        ":<???<<<<<<<<<<<???:@A",
        ":<?????????????????:@A",
        ":<???AAAAAAAAAAA???:@A",
        ":<???AƇƇƇƇƇƇƇƇƇ<???:@A",
        ":<???<<<<<<<<<<<???:@A",
        ":<::::::::::::::::::@A",
        "::;@@@@@@@@@@@@@@@@@@A",
        "Ə9>99999999999999999>9",
    ]

    static let btnEjectPressed = [
        "NNNNNNNNNNNNNNNNNNNNNN",
        "NNNNNNNNNNNNNNNNNNNNNN",
        "NNOPPPPPPPPPPPPPPPPOQN",
        "NNPRRRRRRRRRRRRRRRRRPN",
        "NNPRPPPPPPPPNPPPPPPPPN",
        "NNPRPPPPPPPNANPPPPPPPN",
        "NNPRPPPPPPNAAANPPPPPPN",
        "NNPRPPPPPNAAAAANPPPPPN",
        "NNPRPPPPNAAAAAAANPPPPN",
        "NNPRPPPRRRRRRRRRRRPPPN",
        "NNPRPPPPPPPPPPPPPPPPPN",
        "NNPRPPPNNNNNNNNNNNPPPN",
        "NNPRPPPNAAAAAAAAARPPPN",
        "NNPRPPPRRRRRRRRRRRPPPN",
        "NNORPPPPPPPPPPPPPPPPPN",
        "NNQNNNNNNNNNNNNNNNNNNN",
    ]

    static let colors: [Character: NSColor] = [
        "!": NSColor(hex: 0x272641),
        "#": NSColor(hex: 0x272540),
        "$": NSColor(hex: 0x272640),
        "%": NSColor(hex: 0x26253F),
        "&": NSColor(hex: 0x26253E),
        "'": NSColor(hex: 0x25243D),
        "(": NSColor(hex: 0x25243C),
        ")": NSColor(hex: 0x24223B),
        "*": NSColor(hex: 0x24233A),
        "+": NSColor(hex: 0x24223A),
        ",": NSColor(hex: 0x232239),
        "-": NSColor(hex: 0x232139),
        ".": NSColor(hex: 0x232138),
        "/": NSColor(hex: 0x232137),
        "0": NSColor(hex: 0x222137),
        "1": NSColor(hex: 0x212036),
        "2": NSColor(hex: 0x212035),
        "3": NSColor(hex: 0x211F34),
        "4": NSColor(hex: 0x211F33),
        "5": NSColor(hex: 0x201F33),
        "6": NSColor(hex: 0x201E33),
        "7": NSColor(hex: 0x201F32),
        "8": NSColor(hex: 0x201F34),
        "9": NSColor(hex: 0x2B2A48),
        ":": NSColor(hex: 0x9DA6BA),
        ";": NSColor(hex: 0x718194),
        "<": NSColor(hex: 0xEBFFFF),
        "=": NSColor(hex: 0x415060),
        ">": NSColor(hex: 0x2A2947),
        "?": NSColor(hex: 0xB0C3CD),
        "@": NSColor(hex: 0x687082),
        "A": NSColor(hex: 0x3A4858),
        "B": NSColor(hex: 0x114A01),
        "C": NSColor(hex: 0xCCD5EF),
        "D": NSColor(hex: 0x23293C),
        "E": NSColor(hex: 0x2A2846),
        "F": NSColor(hex: 0x2A2845),
        "G": NSColor(hex: 0x2A2945),
        "H": NSColor(hex: 0x292846),
        "I": NSColor(hex: 0x292844),
        "J": NSColor(hex: 0x292843),
        "K": NSColor(hex: 0x282842),
        "L": NSColor(hex: 0x282742),
        "M": NSColor(hex: 0x292741),
        "N": NSColor(hex: 0x09090E),
        "O": NSColor(hex: 0x516871),
        "P": NSColor(hex: 0x68798A),
        "Q": NSColor(hex: 0x415860),
        "R": NSColor(hex: 0x9EAFBA),
        "S": NSColor(hex: 0x7D8E97),
        "T": NSColor(hex: 0x000000),
        "U": NSColor(hex: 0x1CD304),
        "V": NSColor(hex: 0x2A2946),
        "W": NSColor(hex: 0x292742),
        "X": NSColor(hex: 0x1F1F32),
        "Y": NSColor(hex: 0x201E32),
        "Z": NSColor(hex: 0x1F1E31),
        "[": NSColor(hex: 0x1E1D30),
        "]": NSColor(hex: 0x211F36),
        "^": NSColor(hex: 0x202034),
        "_": NSColor(hex: 0x1B1A2B),
        "`": NSColor(hex: 0x1C1B2C),
        "a": NSColor(hex: 0x1B1A2A),
        "b": NSColor(hex: 0x1A1A2A),
        "c": NSColor(hex: 0x1E1C2F),
        "d": NSColor(hex: 0x1D1D2F),
        "e": NSColor(hex: 0x1E1C2E),
        "f": NSColor(hex: 0x1D1C2E),
        "g": NSColor(hex: 0x1C1B2E),
        "h": NSColor(hex: 0x1C1C2D),
        "i": NSColor(hex: 0x232237),
        "j": NSColor(hex: 0x222237),
        "k": NSColor(hex: 0x222336),
        "l": NSColor(hex: 0x222636),
        "m": NSColor(hex: 0x212835),
        "n": NSColor(hex: 0x202734),
        "o": NSColor(hex: 0x202533),
        "p": NSColor(hex: 0x202433),
        "q": NSColor(hex: 0x202233),
        "r": NSColor(hex: 0x1F2331),
        "s": NSColor(hex: 0x1E2130),
        "t": NSColor(hex: 0x1E202F),
        "u": NSColor(hex: 0x1D1E2E),
        "v": NSColor(hex: 0x222238),
        "w": NSColor(hex: 0x232437),
        "x": NSColor(hex: 0x232637),
        "y": NSColor(hex: 0x222837),
        "z": NSColor(hex: 0x222B36),
        "{": NSColor(hex: 0x212E34),
        "|": NSColor(hex: 0x223036),
        "}": NSColor(hex: 0x213334),
        "~": NSColor(hex: 0x213133),
        "À": NSColor(hex: 0x202E32),
        "Á": NSColor(hex: 0x1F2D31),
        "Â": NSColor(hex: 0x1E2B30),
        "Ã": NSColor(hex: 0x1E272F),
        "Ä": NSColor(hex: 0x1D282E),
        "Å": NSColor(hex: 0x1D252E),
        "Æ": NSColor(hex: 0x1D212E),
        "Ç": NSColor(hex: 0x1C202D),
        "È": NSColor(hex: 0x1C1E2D),
        "É": NSColor(hex: 0x222738),
        "Ê": NSColor(hex: 0x223736),
        "Ë": NSColor(hex: 0x233B36),
        "Ì": NSColor(hex: 0x223E36),
        "Í": NSColor(hex: 0x224334),
        "Î": NSColor(hex: 0x224735),
        "Ï": NSColor(hex: 0x214033),
        "Ð": NSColor(hex: 0x213F33),
        "Ñ": NSColor(hex: 0x203C33),
        "Ò": NSColor(hex: 0x203E31),
        "Ó": NSColor(hex: 0x203C31),
        "Ô": NSColor(hex: 0x1F3B2F),
        "Õ": NSColor(hex: 0x1F382F),
        "Ö": NSColor(hex: 0x1E332E),
        "×": NSColor(hex: 0x1E2C2E),
        "Ø": NSColor(hex: 0x222638),
        "Ù": NSColor(hex: 0x223337),
        "Ú": NSColor(hex: 0x234F36),
        "Û": NSColor(hex: 0x235635),
        "Ü": NSColor(hex: 0x1F8427),
        "Ý": NSColor(hex: 0x23FF06),
        "Þ": NSColor(hex: 0x225A33),
        "ß": NSColor(hex: 0x215632),
        "à": NSColor(hex: 0x225433),
        "á": NSColor(hex: 0x215531),
        "â": NSColor(hex: 0x205430),
        "ã": NSColor(hex: 0x1F512E),
        "ä": NSColor(hex: 0x1E492E),
        "å": NSColor(hex: 0x1E3E2E),
        "æ": NSColor(hex: 0x1D2C2D),
        "ç": NSColor(hex: 0x1D252D),
        "è": NSColor(hex: 0x20662D),
        "é": NSColor(hex: 0x1FD611),
        "ê": NSColor(hex: 0x1FD112),
        "ë": NSColor(hex: 0x21842C),
        "ì": NSColor(hex: 0x20CC17),
        "í": NSColor(hex: 0x1EBF17),
        "î": NSColor(hex: 0x218E28),
        "ï": NSColor(hex: 0x1FD512),
        "ð": NSColor(hex: 0x1D971F),
        "ñ": NSColor(hex: 0x1FDE0F),
        "ò": NSColor(hex: 0x1FCF15),
        "ó": NSColor(hex: 0x21782E),
        "ô": NSColor(hex: 0x1D9221),
        "õ": NSColor(hex: 0x1FD80F),
        "ö": NSColor(hex: 0x1DBE12),
        "÷": NSColor(hex: 0x1D292D),
        "ø": NSColor(hex: 0x1C212C),
        "ù": NSColor(hex: 0x1C1D2B),
        "ú": NSColor(hex: 0x232937),
        "û": NSColor(hex: 0x1FD910),
        "ü": NSColor(hex: 0x1FA121),
        "ý": NSColor(hex: 0x209B26),
        "þ": NSColor(hex: 0x267B37),
        "ÿ": NSColor(hex: 0x21F50C),
        "Ā": NSColor(hex: 0x20DB12),
        "ā": NSColor(hex: 0x20E90E),
        "Ă": NSColor(hex: 0x20E111),
        "ă": NSColor(hex: 0x1FC617),
        "Ą": NSColor(hex: 0x1FBE1A),
        "ą": NSColor(hex: 0x1DB017),
        "Ć": NSColor(hex: 0x1D372D),
        "ć": NSColor(hex: 0x1C222D),
        "Ĉ": NSColor(hex: 0x1C1D2C),
        "ĉ": NSColor(hex: 0x1EB31A),
        "Ċ": NSColor(hex: 0x21F10C),
        "ċ": NSColor(hex: 0x22FE0A),
        "Č": NSColor(hex: 0x20E30D),
        "č": NSColor(hex: 0x246C34),
        "Ď": NSColor(hex: 0x1B6224),
        "ď": NSColor(hex: 0x225134),
        "Đ": NSColor(hex: 0x225533),
        "đ": NSColor(hex: 0x213A35),
        "Ē": NSColor(hex: 0x223B33),
        "ē": NSColor(hex: 0x1C1B2B),
        "Ĕ": NSColor(hex: 0x222235),
        "ĕ": NSColor(hex: 0x202335),
        "Ė": NSColor(hex: 0x212434),
        "ė": NSColor(hex: 0x222136),
        "Ę": NSColor(hex: 0x202033),
        "ę": NSColor(hex: 0x1D1C2F),
        "Ě": NSColor(hex: 0x222138),
        "ě": NSColor(hex: 0x39384E),
        "Ĝ": NSColor(hex: 0x9A99A5),
        "ĝ": NSColor(hex: 0x333346),
        "Ğ": NSColor(hex: 0x797887),
        "ğ": NSColor(hex: 0x706F80),
        "Ġ": NSColor(hex: 0x696779),
        "ġ": NSColor(hex: 0x5E5D6E),
        "Ģ": NSColor(hex: 0x6E6D7C),
        "ģ": NSColor(hex: 0x3F3E50),
        "Ĥ": NSColor(hex: 0x777784),
        "ĥ": NSColor(hex: 0x666575),
        "Ħ": NSColor(hex: 0x232335),
        "ħ": NSColor(hex: 0x646373),
        "Ĩ": NSColor(hex: 0x1C1B2D),
        "ĩ": NSColor(hex: 0x787887),
        "Ī": NSColor(hex: 0x48475C),
        "ī": NSColor(hex: 0x2E2D41),
        "Ĭ": NSColor(hex: 0x898895),
        "ĭ": NSColor(hex: 0x7F7E8B),
        "Į": NSColor(hex: 0x9998A3),
        "į": NSColor(hex: 0x565567),
        "İ": NSColor(hex: 0x5C5C6B),
        "ı": NSColor(hex: 0x91909C),
        "Ĳ": NSColor(hex: 0x5D5D6C),
        "ĳ": NSColor(hex: 0x525263),
        "Ĵ": NSColor(hex: 0x6B6A7D),
        "ĵ": NSColor(hex: 0x272741),
        "Ķ": NSColor(hex: 0x272840),
        "ķ": NSColor(hex: 0x272B40),
        "ĸ": NSColor(hex: 0x262B40),
        "Ĺ": NSColor(hex: 0x262A3E),
        "ĺ": NSColor(hex: 0x25293D),
        "Ļ": NSColor(hex: 0x24283B),
        "ļ": NSColor(hex: 0x24273A),
        "Ľ": NSColor(hex: 0x24263A),
        "ľ": NSColor(hex: 0x23233A),
        "Ŀ": NSColor(hex: 0x272F40),
        "ŀ": NSColor(hex: 0x283140),
        "Ł": NSColor(hex: 0x273340),
        "ł": NSColor(hex: 0x273640),
        "Ń": NSColor(hex: 0x26333C),
        "ń": NSColor(hex: 0x25343C),
        "Ņ": NSColor(hex: 0x243339),
        "ņ": NSColor(hex: 0x24303A),
        "Ň": NSColor(hex: 0x242E39),
        "ň": NSColor(hex: 0x232C39),
        "ŉ": NSColor(hex: 0x232839),
        "Ŋ": NSColor(hex: 0x232739),
        "ŋ": NSColor(hex: 0x232338),
        "Ō": NSColor(hex: 0x283641),
        "ō": NSColor(hex: 0x273B40),
        "Ŏ": NSColor(hex: 0x27423F),
        "ŏ": NSColor(hex: 0x27453D),
        "Ő": NSColor(hex: 0x27423D),
        "ő": NSColor(hex: 0x25453A),
        "Œ": NSColor(hex: 0x253F3B),
        "œ": NSColor(hex: 0x253C3A),
        "Ŕ": NSColor(hex: 0x233739),
        "ŕ": NSColor(hex: 0x284D40),
        "Ŗ": NSColor(hex: 0x27513D),
        "ŗ": NSColor(hex: 0x285A3E),
        "Ř": NSColor(hex: 0x28573E),
        "ř": NSColor(hex: 0x275D3C),
        "Ś": NSColor(hex: 0x26593A),
        "ś": NSColor(hex: 0x26543A),
        "Ŝ": NSColor(hex: 0x254B39),
        "ŝ": NSColor(hex: 0x232838),
        "Ş": NSColor(hex: 0x272E3F),
        "ş": NSColor(hex: 0x22FC0A),
        "Š": NSColor(hex: 0x239B2C),
        "š": NSColor(hex: 0x238530),
        "Ţ": NSColor(hex: 0x20E70E),
        "ţ": NSColor(hex: 0x20C31A),
        "Ť": NSColor(hex: 0x20BA1E),
        "ť": NSColor(hex: 0x238A2F),
        "Ŧ": NSColor(hex: 0x244039),
        "ŧ": NSColor(hex: 0x28693D),
        "Ũ": NSColor(hex: 0x20DE11),
        "ũ": NSColor(hex: 0x20BA1F),
        "Ū": NSColor(hex: 0x20D814),
        "ū": NSColor(hex: 0x27543D),
        "Ŭ": NSColor(hex: 0x25543A),
        "ŭ": NSColor(hex: 0x263D3D),
        "Ů": NSColor(hex: 0x253E3A),
        "ů": NSColor(hex: 0x222438),
        "Ű": NSColor(hex: 0x262640),
        "ű": NSColor(hex: 0x25303D),
        "Ų": NSColor(hex: 0x26283F),
        "ų": NSColor(hex: 0x26273E),
        "Ŵ": NSColor(hex: 0x26283D),
        "ŵ": NSColor(hex: 0x25273C),
        "Ŷ": NSColor(hex: 0x232639),
        "ŷ": NSColor(hex: 0x25253C),
        "Ÿ": NSColor(hex: 0x232238),
        "Ź": NSColor(hex: 0x404058),
        "ź": NSColor(hex: 0x9D9DAB),
        "Ż": NSColor(hex: 0x737285),
        "ż": NSColor(hex: 0x9494A3),
        "Ž": NSColor(hex: 0x838292),
        "ž": NSColor(hex: 0x636276),
        "ſ": NSColor(hex: 0x5B5A6F),
        "ƀ": NSColor(hex: 0x8B8B9A),
        "Ɓ": NSColor(hex: 0x7B7B8B),
        "Ƃ": NSColor(hex: 0x3F3E54),
        "ƃ": NSColor(hex: 0x9C9BA8),
        "Ƅ": NSColor(hex: 0x2A2940),
        "ƅ": NSColor(hex: 0x4D4D63),
        "Ɔ": NSColor(hex: 0x25253D),
        "Ƈ": NSColor(hex: 0x8597AB),
        "ƈ": NSColor(hex: 0x171725),
        "Ɖ": NSColor(hex: 0x181726),
        "Ɗ": NSColor(hex: 0x1A1826),
        "Ƌ": NSColor(hex: 0x191827),
        "ƌ": NSColor(hex: 0x1A1827),
        "ƍ": NSColor(hex: 0x1A1928),
        "Ǝ": NSColor(hex: 0x1A1A29),
        "Ə": NSColor(hex: 0x2A2948),
    ]
}