// Wamp/Skinning/ClassicSprites/ClassicEQSheets.swift
// GENERATED pixel maps extracted 1:1 from base-2.91 sprite sheets
// (scripts in the session scratchpad; re-extract from skins/base-2.91.wsz).
// Baked text and LED art are not worth re-deriving as vector structure —
// exact pixel maps drawn as 1-pt rects stay crisp at every backing scale.

import AppKit

enum ClassicEQSheets {
    static let eqOnOff = [
        "!!!!!!!!!!!!!!!!!!!!!!!!#$",
        "!%%%%%%%%%%%%%%%%%%%%%%!&$",
        "!%''''''''''''''''''''!()$",
        "!%')))))'''**''*''*'''!()$",
        "!%')+++,''*''*'**'*'''!()$",
        "!%')+++,''*''*'****'''!()$",
        "!%'),,,,''*''*'*'**'''!()$",
        "!%'''''''''**''*''*'''!()$",
        "!%''''''''''''''''''''!()$",
        "!%!!!!!!!!!!!!!!!!!!!!!()$",
        "!!#((((((((((((((((((((()$",
        "#&)))))))))))))))))))))))$",
    ]

    static let eqOnOffPressed = [
        "--------------------------",
        "--------------------------",
        "--.//////////////////////-",
        "--/0000000000000000000000-",
        "--/0/////////////////////-",
        "--/0/-----///--//-//-////-",
        "--/0/-+++#//-//-/--/-////-",
        "--/0/-+++#//-//-/----////-",
        "--/0/-####//-//-/-/--////-",
        "--/0/////////--//-//-////-",
        "--.0/////////////////////-",
        "--&-----------------------",
    ]

    static let eqOnActive = [
        "!!!!!!!!!!!!!!!!!!!!!!!!#$",
        "!%%%%%%%%%%%%%%%%%%%%%%!&$",
        "!%''''''''''''''''''''!()$",
        "!%')))))'''**''*''*'''!()$",
        "!%')111,''*''*'**'*'''!()$",
        "!%')111,''*''*'****'''!()$",
        "!%'),,,,''*''*'*'**'''!()$",
        "!%'''''''''**''*''*'''!()$",
        "!%''''''''''''''''''''!()$",
        "!%!!!!!!!!!!!!!!!!!!!!!()$",
        "!!#((((((((((((((((((((()$",
        "#&)))))))))))))))))))))))$",
    ]

    static let eqOnActivePressed = [
        "--------------------------",
        "--------------------------",
        "--.//////////////////////-",
        "--/0000000000000000000000-",
        "--/0/////////////////////-",
        "--/0/-----///--//-//-////-",
        "--/0/-111#//-//-/--/-////-",
        "--/0/-111#//-//-/----////-",
        "--/0/-####//-//-/-/--////-",
        "--/0/////////--//-//-////-",
        "--.0/////////////////////-",
        "--&-----------------------",
    ]

    static let eqAutoOff = [
        "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!#",
        "!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%!&",
        "!%'''''''''''''''''''''''''''!()",
        "!%')))))'''**''*''*'***''**''!()",
        "!%')+++,''*''*'*''*''*''*''*'!()",
        "!%')+++,''****'*''*''*''*''*'!()",
        "!%'),,,,''*''*'*''*''*''*''*'!()",
        "!%''''''''*''*''**'''*'''**''!()",
        "!%'''''''''''''''''''''''''''!()",
        "!%!!!!!!!!!!!!!!!!!!!!!!!!!!!!()",
        "!!#(((((((((((((((((((((((((((()",
        "#&))))))))))))))))))))))))))))))",
    ]

    static let eqAutoOffPressed = [
        "--------------------------------",
        "--------------------------------",
        "-./////////////////////////////-",
        "-/00000000000000000000000000000-",
        "-/0////////////////////////////-",
        "-/0/-----///--//-//-/---//--///-",
        "-/0/-+++#//-//-/-//-//-//-//-//-",
        "-/0/-+++#//----/-//-//-//-//-//-",
        "-/0/-####//-//-/-//-//-//-//-//-",
        "-/0////////-//-//--///-///--///-",
        "-.0////////////////////////////-",
        "-&------------------------------",
    ]

    static let eqAutoActive = [
        "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!#",
        "!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%!&",
        "!%'''''''''''''''''''''''''''!()",
        "!%')))))'''**''*''*'***''**''!()",
        "!%')111,''*''*'*''*''*''*''*'!()",
        "!%')111,''****'*''*''*''*''*'!()",
        "!%'),,,,''*''*'*''*''*''*''*'!()",
        "!%''''''''*''*''**'''*'''**''!()",
        "!%'''''''''''''''''''''''''''!()",
        "!%!!!!!!!!!!!!!!!!!!!!!!!!!!!!()",
        "!!#(((((((((((((((((((((((((((()",
        "#&))))))))))))))))))))))))))))))",
    ]

    static let eqAutoActivePressed = [
        "--------------------------------",
        "--------------------------------",
        "-./////////////////////////////-",
        "-/00000000000000000000000000000-",
        "-/0////////////////////////////-",
        "-/0/-----///--//-//-/---//--///-",
        "-/0/-111#//-//-/-//-//-//-//-//-",
        "-/0/-111#//----/-//-//-//-//-//-",
        "-/0/-####//-//-/-//-//-//-//-//-",
        "-/0////////-//-//--///-///--///-",
        "-.0////////////////////////////-",
        "-&------------------------------",
    ]

    static let eqPresets = [
        "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!#",
        "!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%!&",
        "!%'''''''''''''''''''''''''''''''''''''''!()",
        "!%'''***''***'''***''***''***'***''***'''!()",
        "!%'''*''*'*''*'*''''*''''*'''''*''*''''''!()",
        "!%'''***''***''****''**''****''*'''**''''!()",
        "!%'''*''''*''*'*'''''''*'*'''''*'''''*'''!()",
        "!%'''*''''*''*''***'***'''***''*''***''''!()",
        "!%'''''''''''''''''''''''''''''''''''''''!()",
        "!%!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!()",
        "!!#(((((((((((((((((((((((((((((((((((((((()",
        "#&))))))))))))))))))))))))))))))))))))))))))",
    ]

    static let eqPresetsPressed = [
        "--------------------------------------------",
        "--------------------------------------------",
        "--.////////////////////////////////////////-",
        "--/0000000000000000000000000000000000000000-",
        "--/0///////////////////////////////////////-",
        "--/0///$$$//$$$///$$$//$$$//$$$/$$$//$$$///-",
        "--/0///$//$/$//$/$////$////$/////$//$//////-",
        "--/0///$$$//$$$//$$$$//$$//$$$$//$///$$////-",
        "--/0///$////$//$/$///////$/$/////$/////$///-",
        "--/0///$////$//$//$$$/$$$///$$$//$//$$$////-",
        "--.0///////////////////////////////////////-",
        "--&-----------------------------------------",
    ]

    static let eqThumb = [
        "2-$$$$$$$-2",
        "-33333333)-",
        "-3000000()-",
        "-3000000()-",
        "-300---0()-",
        "-3000000()-",
        "-300---0()-",
        "-3000000()-",
        "-3#(((((()-",
        "-3))))))))-",
        "2-$$$$$---2",
    ]

    static let eqThumbPressed = [
        "2$$$$$$$$$2",
        "$33333333)$",
        "$3$$$$$$$)$",
        "$3$$$$$$$)$",
        "$3$$%%%$$)$",
        "$3$$$$$$$)$",
        "$3$$%%%$$)$",
        "$3$$$$$$$)$",
        "$3$$$$$$$)$",
        "$3))))))))$",
        "2$$$$$$$$$2",
    ]

    static let eqGraphBg = [
        "45677889::;<<<6==>>>>>?@@@ABBBCDDEEFEFGHHIIJJJJKKLMNOPPPPQQQQRSTUVUWTXTTTYZ[XY[Y[]]]]]^]Y]]]]]]]]]^]]]X[[]YYXXZTT",
        "__657989::;;<`6=>=>>>aa@@@ABBDDbDEEEFFGHHHcJJJLJKNMPKOPPQQPQQRSWWUVTTTXX[XZYYX]]YYY]]]^]]]]]]]]]]Y^Y]YYXY[XXXTZVT",
        "__67799::;;<<`6==>>>>>a@@@ABBDDDDEEFFFGIHIJJJJJKdKMOPPPPQPQQRQSWTVTTTTXXX[Z]YXX[Y]YYY]^]]]]]]]]]]]^]]]XYXYXTYXeTT",
        "556fff::;;<<<g6=>=>>>?@@@BABhBDDDEFFcFGHiHJJJJJKLjMPPPPQPQQQRReRVWVTTTXYXY^X][]][]k]]]^]]]]]]]]]]]^]]X]]XXXXTTeTT",
        "_767ff9:::<<l=6==>>>a?@@@BADBDDEEEEFFHGccIJJJJKLKjMPPPPPQPRQRRSUWVTTTTTXXYZ[]]]]]]]]]]^]]]]]]]Y]]]ZY]XX]XY[TXTSTT",
        "556f99::;;<<mm6==>>>>@?@@BABbbDEEEFFHiGiJJJLJLKNLKMPPPPPQRQQRRSUTTTTXXY[[YZ]]]]]][]]]]^]]]]]]]]]]Y^][Y]YXTYXTXeTV",
        "776989::;n<<`n6>=>>a>@@BBBABDDDDEFFFFHGcIJJJLLLdjjMPPPQPQRQRRReVRTTXXTTTYY^YY[[Y][]]]]^]]]]]]]Y]]]Z]]]Y[XYTTTTSVU",
        "5569:::;;;<<==6>>>>a?@@BBBABDDDDFFFHFHGJJJJJLKKKOPMPPPPQQQQRRRSWTTTTTTYTXkZYX]]Y]]]]]Y^]]]]]]]]]YY^]YYYXXXXTTTSTT",
        "776f9:::<<<<==A>>>>?@@BBBBABDDEEEFFFHiGHJJJJLLLNjoMPPPQQQRRRUReRUTTTXTYXYY^]Y][]]]]]]]^]]]]]]]]]]Y^]Y[YXXYXTTTeTT",
        "57699::;;`gg==6>>>>>@@@BBBABDDEEEFHHHHGJJJJLJLjKNoMPPPPQQRRRVWSUWTXTTXX[YkZYY]]]]Y]]]]^]]]]]]]]]]]^[kY]XTXTXVWSTW",
        "5f68:::;;<g===A=>>>?@@@BBBABDDEEFFHHHcGJJJJLJjKjjPMPPPPRRQRRRRSWTTTTYXY[YX^kkY]Yk]Y]]]^]]]]]]]]YYY^Y[]Y[XTTTXTeTU",
        "7f6f:::;<<l===A>>>a@@@BBBDAbEEEFEFFHHHGJJJJLLKKKjPMPPQQQQRRUWRSWTTXXX[YXXX^YY]]]Y]]]]]^]]]]]][Y]Y]^]YY[[[TXVTVeWW",
        "ff69:;;;<gnl==A>>?a@@@BBBBADEEEFFFHIiiGJJJJLKKjOPPMPQPPQRRRWRUSTTTT[XXYXX[^Y]]]]]YY]]]^]]]]]]]]YY]^Y[X[YXTTTTReWT",
        "7969;:;<<=l==>A>>a?@B@BBBBAEDEFEFHHHIHGJJJLJLKNjPPMPQQQRRRRRRRSTVTXXXTXYY]^Y]]]]]]]]Y]^]]]]]Y]]]YkZYY[XXXXTTVTSRW",
        "f86::;;<<l==>=A>a?@@BBBBDbADEFFFFFHHIHGJJLLLNjoKNPMPQPQQRURURWeTTTTTT[XXXk^YY]]]]]]]]]^]]]]]]]Y]Y]Z[XYYXXTTTTTSRR",
        "8:6:;:;<<`===>A>?@?@BBBBDbAbEEFFFIIIcJGJJJJKKjOPPPMQQQQQRRWRUWSTTTTXTYXYX]^[Y][][]]]]]^]]]]]]Y]]]]^[YXTYXTTTTUeUR",
        "996;;:<<ll==>>A???@B@BBBbDADEEFFFIHJcJGLLLLKKjKPPPMQQPRRRRRVTTeTTTXTX[YYYX^Xk]]]]]]]]]^]]]]]]kYYXX^XX[XXXVTTTTeRR",
        "f96;;;<nml=>>>A?aa@@@BBCDDADEFFFFHHJHJGJLLKKNOPPPPSQPRRQRRUUUReXXTTXY[[Y]Y^]]]]Y[Y]]]]^]]]]YYYY]]YZXYYTTTXXTTUSRR",
        "9:6:;<<m===>>>A?@?@@BBBDbDGEEEFFFHIIJJGJJLKKoNNPPPSQQQRRRRUTRWeTTXX[YXYYYY^]]]]]]]]]]]^]]]]]YY][YY^Y[XXXTVVTVRSRR",
    ]

    static let eqLadder = [
        "p4q__57fff:::;<<`=m=>>>>aa?@@BBDBDEDEEFFHFHcJJJJJLJKKjjPPPPQPQRQRRRVRVRVTTTXX[X][Y]Y]]]]]]]]]]]]]]]]]Y]]]]]]Y[[XTTXTUT",
        "p445677889::;<<<6==>>>>>?@@@ABBBCDDEEFEFGHHIIJJJJKKLMNOPPPPQQQQRSTUVUWTXTTTYZ[XY[Y[]]]]]^]Y]]]]]]]]]^]]]X[[]YYXXZTTWTU",
        "r4__657989::;;<`6=>=>>>aa@@@ABBDDbDEEEFFGHHHcJJJLJKNMPKOPPQQPQQRSWWUVTTTXX[XZYYX]]YYY]]]^]]]]]]]]]]Y^Y]YYXY[XXXTZVTRTU",
        "qs__67799::;;<<`6==>>>>>a@@@ABBDDDDEEFFFGIHIJJJJJKdKMOPPPPQPQQRQSWTVTTTTXXX[Z]YXX[Y]YYY]^]]]]]]]]]]]^]]]XYXYXTYXeTTTWT",
        "qq556fff::;;<<<g6=>=>>>?@@@BABhBDDDEFFcFGHiHJJJJJKLjMPPPPQPQQQRReRVWVTTTXYXY^X][]][]k]]]^]]]]]]]]]]]^]]X]]XXXXTTeTTTRW",
        "r__767ff9:::<<l=6==>>>a?@@@BADBDDEEEEFFHGccIJJJJKLKjMPPPPPQPRQRRSUWVTTTTTXXYZ[]]]]]]]]]]^]]]]]]]Y]]]ZY]XX]XY[TXTSTTUVU",
        "4_556f99::;;<<mm6==>>>>@?@@BABbbDEEEFFHiGiJJJLJLKNLKMPPPPPQRQQRRSUTTTTXXY[[YZ]]]]]][]]]]^]]]]]]]]]]Y^][Y]YXTYXTXeTVWUR",
        "__776989::;n<<`n6>=>>a>@@BBBABDDDDEFFFFHGcIJJJLLLdjjMPPPQPQRQRRReVRTTXXTTTYY^YY[[Y][]]]]^]]]]]]]Y]]]Z]]]Y[XYTTTTSVUTWU",
        "55ff69:::;;;<<==6>>>>a?@@BBBABDDDDFFFHFHGJJJJJLKKKOPMPPPPQQQQRRRSWTTTTTTYTXkZYX]]Y]]]]]Y^]]]]]]]]]YY^]YYYXXXXTTTSTTWWR",
        "7t9f6f::::<<<<=>A>????@@BBBBABDDEEEFFFHiGHJJJJLLLNjoMPPPQQQRRRUReRUTTTXTYXYY^]Y][]]]]]]]^]]]]]]]]]]Y^]Y[YXXYXTTTeTTRRR",
        "786666666666666AAAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGMMMMMMMSSSSSSSeSSSSeZeZZZZZZZ^Z^^^^^^^^^^^^^^^^^^^^^^ZZ^^ZeZZZeSSSSTUR",
        "99::6:;;<<<==>>>A>@@@BBBBBDDADDEFFHHccccGJJJJLJjKjjPMPPPPRRQRRRRSWTTTTYXY[YX^kkY]Yk]Y]]]^]]]]]]]]YYY^Y[]Y[XTTTXTeTUURR",
        "::::6:;<<g==>>>>A@@@BBBBbhDEAEFFFIFIIJJJGJJKJLLKKKjPMPPQQQQRRUWRSWTTXXX[YXXX^YY]]]Y]]]]]^]]]]]][Y]Y]^]YY[[[TXVTVeWWURQ",
        ";;<<6;ng=`==>>??Aa@BBDBDBhDDAFFFFiHIJLJJGLLKKKooPPPPSPRRRRRRRWRUSTTTT[XXYXX[^Y]]]]]YY]]]^]]]]]]]]YY]^Y[X[YXTTTTReWTRQQ",
    ]

    static let eqDbRowTop = [
        "uvwxyz{47;=>@@@@>=:7p|}~yÀÁÂÂÂÂÂÁÁÁÁÀÃÃyyy~~Ä~ÅÆÆ}}}}{Ç{|Èp45f::<=>@BBBBBBAB@@BBBBBbDFGHIHIJHJIciIGJJJLKNPPPPPSPPPPPPQQQRReTTTTTTTTXTXZXXXX[YXYYYY^]]]]]]]]]]]^]]]]]YY][YY^Y[XXXXXXXXTZTTUTRRRRQQQQQRQQPPPPKKLLJJJJJJJJJJJHFFEDbhDBBDbDDDDDBB@>><;:9__pÈÈÉ{{{{",
        "uvwÁÄÇp7;>@BDEDDB>=:5È{Å~yÁÀÁÂÂÂÂÁÁÊÃÃËyy~Ä~~ÅzÅÌÆ}Ç{{{ÍÈÈp559:<=>@BBDEDDDDBBBBBBDDEEFiIJJJJJJJJJJJJJLKKPPPPPPQQPPPQQQRRRVVWTTTTTTXTXXXXXYXYXXX[]]]]]]]]]]]]]]]]]]]]]]][[YYXXXXXXXXXXTTTTVUURRRRQRRRQRQPPPoPNKLJJJLLJKLLLJIJHFEEDDDDDEEEEEEDB@?>=;:f7sqpÈÉÉ{{{",
        "ÎÏxÃÅÍq:>@bFHIHFEB>=:qÈ}~~ËÀÁÁÁÁÂÁÀÐÐËyÐÐ~~~~zÐÆÐ}}Ç{{{|Èpp7f:;l>@BDEFFFFEEDDBBBBDEFFHJLLLLLJJJLJJJJKKKPPQQQQRPPQQPQPRRRRVWTTXXXTXTXXXXXXXYXY]]]]]]]]]]]]]]]]]]]]]]]k]]X]X][YXXXXYY[XYTTWTUURRRRRRRRRRRRPPPNNLLLLLKLKKKKLLJJHHFEEEEEEFFFHFFEDB@>=<;f5qpp|É{{Ç}",
        "vwÁ~}Ñf=@DFJJLJJHEB><5p{Æ~ËÒÁÁÁÂÐÊÁÁÐÃÃÄyÐ~~zÅÐÆÐÌ}{Ç{{ÈÈp459:<>?@BEFHHHHFFEDDDDDEEFHJJLKKjNKKLJJLLKKKPPQRQRRRRQQQQQRQRRURTTXXXYXTTXXXXXYX[Y]]]]]]][]]]]Y]]]]]]]]]]]]]XYYYX[X[XXYYYYXXXTTTTRURRRRRRRWRRRQPPPPKKKKKKKOOPPKjLJJHFFEEEFFFHIJIIFEbB?>g:97q4Ñ|É{{Ç}",
        "ÓÔÕÕÕÕÕ>BFJLKOKKJHD@=ÕÕÕÕÕÕÃÊÁÁÐÐÐÀÃÐyyÐÐÐ~~ÐÐÐÌÐÐÐ{Ç{|ÍÈp_ÕÕÕÕÕÖÖEFHJJJJHHFEÖÖÖÖÖÖÖJJKKOPPPOKLÖÖÖÖÖÖÖPPQRRRRRRRQÖÖÖÖÖÖÖRTTTXX[XY[TÖÖÖÖÖÖÖX]]]]]]]]]]ÖÖÖÖÖÖÖ]]]]]]]]]][ÖÖÖÖÖÖÖX[YYXY[X[TTÖÖÖÖÖÖÖRWRWUUURRQPÖÖÖÖÖÖÖKjPPPPPPKLJÖÖÖÖÖÖÖFHJJJJJHFEBÖÕÕÕÕ7_pÑÈ|{{ÇÌ",
        "ÓxËÆÈ7=@EILPPPPPKJFB>;7p{ÅÄyÃÊÀÁÐÀÊÃÐÃyÐÄ~~~ÐÆÐÆÐ}Ð{{{ÉÑp455:;=>@DFIJJLLJJIFFEEEFFFJJLNPPPPPPPjKKKOOPPQPRRRRTRRRRRRRRRRRTTTXXXYXXXYXXXXX[Y]]]]]]]]]]]]]]]]]]]]]]]]]]]]]XX[XXXXYYYY[YXXXTTWWWRRRRRRVTTTWRRQQPPOKOKKNPPPPPPPOKJJIFFFFFHJJLLJJJIFD@>=;:f_ppÈ|Ç{}}",
        "ÔÁ~{4:>BFLKPQQQPPLHE@=fr|ÆÅyÃÊÊÁÁÊÀÐÐÐyÐÐÐ~~ÐÐÐÆÐÐÐ{Ç{|Ñp4_9:<>@BEHJLKKKKJJIIFEEFFIJLKPPQQQQPPPOKKOPPPPRRWUTTTTRRURRRRRTTTXXXXXXY[XYXXXXY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]Y[YXXY][Y[Y[XYXTTTWTRRRTUWTVTTTWRRQPPPOKKPPPQQPQPPPOLJJHFFFHIJLKKKKLJFEB?=<:t_pÈÑ|{Ç}}",
        "ÔÁz|_<@DIKPQRRRRPNJFB>;_È{Å~ËËÀÒÊÁÃÃyË~~Ä~~zÆÆÆÌ}}ÇÇ{{ÈÈ4579;l>@DEIJKPPPKKLJHHFFFHJJLPPPQRRQQQPPPKPPPPQRWTTTTTVTWRURRRTTTXXXXYXXXYYY]XX[]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]][X[YYY]Y[XYYXXXTTTRRRUUWTTTTTTTRRQPPPKjPPPPQQQRQQPKKJJiHHIIJJKoOPKKJiEB@><:9_4ÈÍ|{{}Æ",
        "xÃÆÈ7=@EJPQRTTTRQPLHD>;5È{Ì~yyÃÃÀÁÃÃËy~~Ä~zzzÆÌ}}Ç{Ç{|Èpp_f:;=>BDFJLKPPPPNKJJiHHHJJLKPPQRRRRQQPPPPPPPPRRRTTTTTTTVURTTTTTTXXYYYY][YXYY]Y]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]Y[YX]YYYYXXTTTTTTUVWTTTTTTTVRRPPPPPjPPPQRRRRQPPKJJJIIHJJKKPPPPKLJFD@>=:f_qÈÍÍ{}}}",
        "Ây}p:>BHLPRTTTTTRPKJE@=f4{Ìz~ÃËÀÃÊÃËyyyÄ~~zzÅÆÆÌÇÇ{{{ÈÑp4_f:<>@BEHJKPPPPPPKKJJIHiJJLoPQRRWRRRQQPPPPPPQRUTTTTXTTTTWRTTTTTXXXYYYY][[YYY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]Y]YYY[XY]]YYXXXTTTTTRVTTTTXTTTTURQPPPPPPPQRRRRRRPPKLJJHcJJLKPPPQPPKJHD@>l;754ÈÈÍ{}}}",
    ]

    static let eqDbRowMid = [
        "Í5<@FJPRTXY]]]]]]XTRPKiD@n8_Í{}}ÆzzzÅÆÆÆÌÇ{Ç{{{ÍÈÈp45_5::<>@BEHLNQRTTXXXXTVRRQPQPQQRTTXXYYYYXXXTTTTTTXXXY]]]]]]YYXYXXXYY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]YYYYYYY]]]]]]]YXXXTTTTTXXXYYYYXXTTRRQQQRRTTTXXXXXTRRQPPPKPPQRTTTXTTRPKJFD@=:54Í|ÇÆÅ~~",
        "Í7l@FJPRTXY]]]]]]XTRPKID@m:_È{}ÆÆz~zÆÆ}}}}Ç{{{ÍÍÈÑp275f:<l>@BEHLPPRTTXXXXTTRRQPPQQRRTTXXYYYYXXXTTTTTTXXXY]]]]]]YYYYYXYYY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]YYYYY]Y]]]]]]Y[XXXTTTTTXX[YYYYXXTTTRRRRRRUTTXXXXXTRRQPPNPPPQRTTXXTTRPKJFB>=:f4È{ÇÆz~~",
        "È7<@FJPRTXY]]]]]]XTRPKIE@=:qÈ|ÇÆÆzÅzÆÆÐÐÇ{Ç{ÍÐÉÐÈÈÈ4_5f:nl>@DEILPQRTTXXXXTTRRQQPPQRWTTXXYYYYXXXTTTTTTXXYY]]]]]]YY[YYXYYY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]YYXYY[]Y]]]]]]]XXXXTTTTTXXYYYYYXXTTWRRQRRRRTTXXXXXTWRQPPNPPPQRTTTXTTRPKJFBa=:54Í{}Æz~y",
        "È7<@FLPRTXY]]]]]]XTRPKIE@=:qp|{}ÆÐzÆÆÐÌÇÐ{{{{ÐÍÐÈpp4qff;<=>@DEILPQRTXXXXXTTRRQQQQQRRTXXXYYYYYXXTTTTTTXX[Y]]]]]]YYY[YX]YY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]Y[YYYYY]]]]]]YYYXXTTTTTXXXYYYYYXTTWRRQRRRRTTXXXXXTRRQPPKPPPQRTTTXTTRPjJFB>m:74É{}Æz~y",
        "È7ÕÖÖÖÖRTXY]]]]]]XTRPÖÖÖÖÕÕ_È|Ç}ÐÐÐÆÆÐÌ}Ð{{ÐÐÐÈÐÐÐps77f:<=>ÖÖÖÖÖÖÖRTXXXXXTTRRÖÖÖÖÖÖÖTTXYYYYYXXXÖÖÖÖÖÖÖXY]]]]]]]YYÖÖÖÖÖÖÖ]]]]]]]]]]]ÖÖÖÖÖÖÖ]]]]]]]]]]]ÖÖÖÖÖÖÖ]]]]]]]]]]]ÖÖÖÖÖÖÖ]Y]]]]]]YXXÖÖÖÖÖÖÖXXXYYYY[XTTÖÖÖÖÖÖÖRTTXXXXXTRRÖÖÖÖÖÖÖQRTTTXTTRPKÖÖÖÕÕ;74ÈÍ}zz~y",
        "È7l@FJPRTXY]]]]]]XTRPKJE@=:_pÍ{}ÆÐzÆÆÐ}}ÐÇ{ÐÍÐÍÐpÐp257f;<=a@DFJLPQRTXXXXXTTRRRQQQQRWTTXXYYYYXXXTTTTTTXX[Y]]]]]]YYYYYX]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]Y]Y[YYXYY]]]]]]YXXXTTTTTTXXXYYYYXXTTWRRQQRRRTTXXXXXTRRQPPKPPPQRTTXXTTRPjJFB>l:74È{}zz~y",
        "Èf=@FJPRTXY]]]]]]XTRPKJE@=:5p|{ÌÌÆzÆÌ}ÐÐ{Ç{ÐÐÐÈÐÐÐps7f8;<=>@DFILPQRTXXXXXTTRRRQQQQRTTXXYYYYYXXXTTTTTXXXXY]]]]]]YYYYY[]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]YYYXYYYYY]]]]]]YXXXTTTTTTXXXYYYYYXTTWRRQQRRRTTXXXXXTRRQPPKOPPQRTTTXTTRPKJFB>n:7p|{Ìzz~Ã",
        "È7=BFLPRTXY]]]]]]XTRPKJE@=:5p|Ç}ÌÆÅÆ}}ÇÇ{{{{ÍÍÈÈpp427f8;<=>@DEJKPQRTXXXXXTTRRRQQQQRWTXXXYYYYYXXTTTTTTXXXY]]]]]]]YYYYXY]Y]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]YYXYYYYY]]]]]]YXXXTTTTTTXXXYYYYXXTTWRRQQRRRTTXXXXXTRRQPPKNPPQRVTTXTTRPKJFB>g:5pÍ{Æzz~Ë",
        "È7=@FJPRTXY]]]]]]XTRPKJE@=:5ÈÍÇÇÆÌÆÆ}}Ç}Ç{{ÉÍÈÑÈppr57ff;n=>@DFHLPQRTXXXXXTTRRRPQQQRVTXXYY]YYYXXTTTTTXXXYY]]]]]]]]YYYX]Y]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]YXYYYYY]]]]]]YXXXTTTTTTXXXYYYYXXTTRRQQQQRRTTXXXXXTRRQPPKOPPQRRTTXTTRPKJFB>m:_Ñ|}Æz~ÄÃ",
        "È7=@FJPRTXY]]]]]]XTRPKJE@=:5ÈÍ{}ÌÆÅÌ}}ÇÇ{{{ÍÈÈÈp4442779;n>>@DFcLPQRTXXXXXTTWRQQQQRRUTTXXYYYYYXXXTTTTXXYYY]]]]]]Y]YYXYX]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]YYXXXYYYY]]]]]]YXXXTTTTTTTXXXYYYXXTTRRQQQRRRTTXXXXXTRRPPKKKPPQRRTTXTTRPKJEB><9_p{{Ìz~ÄË",
    ]

    static let eqDbRowBottom = [
        "Ä}È5<@DiKPRWTTTVRPOJFB?=:54È|{{{{{|ÍÈÈÈppp4q___57988;:<l=>a@BDFHJKPPQRRRRRQPPPPoPPPPRRTTTTTXTTWUTVTTTTTXXYYYY][X[YY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]Y]YYYYYYYYYYYXXTTTTTRRRTTTTTTTTURRPPPPPPPPPQRRRRQPPKJJIHHiJJKKPPPPOLJHEEBBBDDEHJJLLLJFDB><94ÍÇÌzÄËÀÁÂÂ×",
        "yÆ|_;>BFLPQRWTWRRPKJEB>g:_pÈÍ{Í{{{ÍÍÈÈpÈ4p_4__7798:9:;ng=>>@BDEFJLOPPQRRQQPPOKPNOPPQRRRTTTTTTTVTWRRVTTXXXXX]YXYYY]]XXX]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]XX[YYY[YYXYXXXXTTTRRRURWTTTTTTTRQQPPNKKOKPPQQQQQPPKKJJHHFHHJJLKjOKKJIFEBB@@BBDFHJJJJHEB@=;74È{Æ~~yÀÁÂÂx",
        "yÅ|q:=BFJKPQRRRRPPLiE@=:fqp|É{Ø{{{ØÐÐÈÈÐÐ4s__5Ð7Ð:9:::;g=>>@@DDFIJKPPQPQQPPPOPKKoPPQQQRWTTTTTWTVRRWTUTTTXXXYXYXXYYX[XY[]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]][XXXXYYXYYYXXXXTTTRRRRRRRRWWTTURRQPPPPLLKjPPPPPQPPPLLJHFFFFFHJJLKKLLJHEDB@@@@BDEFHIHHFDB>=9_Ñ{}ÅÄyyÀÁÂÂx",
        "Ë~{p7g@DiLPPQQQPPKJFB@=:74ÈÍ{{{{{{ÉÉÐÈpprÐs_55ÐfÐ9::;;<l=>>@BDEFiJKoPPPPQPPPjKKKKoOPQRRURTTTWURRRRRRTTTXXX[YXYYYYXXX[YYk]]]]]]]]]]]]]]]]]]]]]]]]]]]]][XXXXXXYYXXXXXXTTTRRRRRRRRRRVWRRRRPPojKKLLLKPPPPPPPKJJHFFFEEFHIJJJJJJHFDB@?>?@@BDEFFFEDB@=nfqÈ{Ìz~ËÀÁÂÂxx",
        "ÃÄÕÕÕÕÕBFJLOPPPPKJHEBÕÕÕÕÕÕÉ{{ÇÐÐÐÍÈÐÈpÐÐÐ__ÐÐÐ7ÐÐÐ::;;n=>>ÕÖÖÖÖÖÖLKNPPPPPPKKÖÖÖÖÖÖÖPQRRUUTWRURÖÖÖÖÖÖÖTXX[X[[YY[XÖÖÖÖÖÖÖY]]]]]]]]]]ÖÖÖÖÖÖÖ]]]]]]]]]]XÖÖÖÖÖÖÖTYYYXXXTTTRÖÖÖÖÖÖÖRRRRRRRRPPPÖÖÖÖÖÖÖLKNPOPNKLJHÖÖÖÖÖÖÖEFHIJJHHFEBÖÖÕÕÕÕÕ?BBDEEDB@>=ÕÕÕÕÕÆ~~yÁÁÂÂx×",
        "Ò~Æ|4:=@DHJLKOKKLIEB@=:fspÍÉ|{{{É|ÍÍÐÈpÐpqq_Ð7Ð9Ð:Ð:;<<==>>?BBDFFIJLKPPPPNKKLKLLLOjPPPQRRRWRURRRRRRRTWTTXYYX[YYXXXX[X[[YYk]]]]]]]]]]]]]]]]]]]]]]]]]YXXXXXXXXXX[XXXXTTWRRRPPQQQQQRRRQQPPPPKLLLJJJLJLKKKLLJiFFEDDBDbDEFFFHFFDBB@>>==>>>?BBBBB@>=;f_p{ÇÅ~yÃÀÁÂx×Ô",
        "Êyz{pf<>BEFJJLJJIFb@><:54ÈÈ{{{{{{ÍÉÐÐÐpÐÐÐ__ÐÐÐ9ÐÐÐ:;;<=m>>@@BDDFHIJLKNjKKKLKJLLKdNjPQQRRRRURRRRURRRUTTTTXYYYYXXX[XXXYXYYYY]]]]]]]]]]]]]]]]]]]]]]]YXXXXXXXXTXXX[TTXTTRRRRRQQQQQQQQQQQPPPKLJJJIJJJJJLLJJJiHFEbhBBBBDDEEEEEDBB@>>==g<m=>>@@@>>=<8_rÍ{ÆÅ~ËÃÀÂÂxxx",
        "Âyz}Í_:=?BEFHHHHEDB?=:f_pÑÉ{{{{{|ÍÈÈÈÑ4r4___557f9:;;;<<=l>a?@BBEFFHJLLLLKKLJJJLLLLKPPPPQQQQRRQPRRRRUTUUTTTXTXXXXXXXXYYY]YY]]]Y]]]]]]]]]]]]]]]]][YYYXXXXXXXXXXTTTTTTTURRRRRQPPPPQPPPPPPPLLJJcHcIiIJIJJJJIHFEDDBBBB@BBBDDDBB@>>==;;:;<`g=>>>==<:7rÈ{}Æ~~ËÀÂÂxxxx",
    ]

    static let eqLabelStrip = [
        "ÙÚuuÛÙÚvvvÏwÔÔÂÒÄÆ{p5:=@@DEEEDB@>=<f5pÈÍ{|Í{{{ØÈÍÈÈp4r2___7fff::;;n<<lm>>>@@bCEFFHÖÖJJLÖÖJJLJJJJKKPÖPÖÖÖRQÖÖRRQRRRVTUÖÖTXÖXXÖÖXXYXXX]]ÖÖY]]ÖÖ]]]ÖÖ]]]]]]]]XÖ[ÖYÖY[XXXXXXXXTTÖÖTTÖWÖURQQQPQPPPPPÖÖPPÖKÖLJIIHHHHHHÖJÖÖHFÖDÖBB@@@@@@BÖBB@Ö@Ö>Õm<;:::::<Õ<mÕÕ;:ÕqÕÍÇÌÅ~yÃÀÂÂÂ×ÔÔÔÜÜÚvÏÛ",
        "ÙÚÎÝÛÛÚvvvwwx×ÁÀyzÕÕ4fÕÕa@ÖÖÖB@Õ=<Õ7ÕpÕÕ{{Ç{{{ÍÍÍppp4r__557f99:::;;<====>>@BBDEFFÖIJJJÖJJÖJJJJJLKKKÖPPPÖPÖQQÖQRRRWWUUTTÖXÖXÖXXÖ[YXY]YÖ]]YYÖ]YÖ]Ö]]Ö]]]]]]YYÖ[Ö[ÖYXYXXXTTWTXTTTÖRÖRÖRQQPPPPPoPOÖPKjjÖLÖJJJHHHFFFFÖFFFÖEÖDÖBB@??>>a?Ö@?ÕÕ>Õ=Õ;::8ff9f:Õ;Õ::97ÕpÕ|}Æ~~ËÁÁÂxÂxxÔÔÜÜÚÓvÛ",
        "ÙÚÞÎÙÙÚvwÏwwwxxÁy~Õ{Õ_Õ;Õ>Õ?>>Õ=Õ:ÕÕÕÈÕÉÕØ{{||ÍÈÈpppr44_755fff:;;;`<<m==?a@BBBEEFÖÖÖJcÖJJÖiJJJLLJKOÖPPÖPPÖQQÖQRRRRRWWÖÖXTÖXÖXXÖTXXX]YÖÖÖ]]Ö]]Ö]Ö]]Ö]]]]]]]YÖXÖÖYXYYXTXWTTTTXÖÖUWÖÖQQQQQPOOPPPoÖÖÖOKÖÖLJIHFFFFFEFÖFEEÖDÖÖB@?>?>>>>>Õ>Õ>Õ>ÕÕ;::7577777ÕfÕÕÕ5qÕÕ|{Æz~yËÀÁÂx×xÔÔwÜÜÚÓvÛ",
        "ÙÚuÎÙÛÚvvÓÓwÔxxÀÒ~ÕÕ{pÕÕ:;ÕÕmnÕÕÕfÕÕÕÍÕÕ{{{{ÉÉÍÍÈppp4sq_57f8:9::<<<<`==>>?@@BBDEFÖFHÖIÖJIÖIJJJJJLßKÖPPÖPQÖQQÖRQRRRWRWWTÖXÖXÖXTÖYY[XX[Ö]YÖ]Ö]]Ö]Ö]]Ö]]]]]]Y]ÖYÖÖYXY[XXTVTTWWWWUÖRÖÖQQPQQPPPONKKÖLLÖLÖÖIHFcFFEEFEDÖEDÖBBÖÖ?a>>>====>Õ>ÕÕÕ<ÕÕ:ff5____q_Õ_Õ_4ÕpÕÕ{}Æ~ÄyÀÁÁÂÂ×xÔwwÜÜÚvvÛ",
        "ÙÚÝÞÙÛÚvvwwwwxxÂÁyÕÅà|Õ4ÕfÕ:::Õ7ÕqÕÈÕØÕ{{{{{ÉÍÍÈÈpp44___77f889:;;;<l===>>?@@BBDDDÖFHÖIÖHiÖIJJJLLLdLÖNÖPPPÖQQÖQRRRRRRRWVÖVÖTÖXTÖX[XY]]Ök]Ö]Ö]]Ö]Ö]]Ö]]]]Y]]]Ö[ÖYÖXXXTTVVTTRURWRÖRÖRÖQPPPPPPjNdLÖLJÖJÖcÖHHFFEDDDDDÖBÖDBBÖ@Ö>>>>==<lgÕng;Õ:Õ:Õ75s_4p444Õ4ÕppÕÍÕÇÕÆ~ÄyÃÀÁÂÂÂxxÔwwÜÜÚvvÛ",
        "ÙÚÝáÛÛÚvwwÓwwÔÂÁÁÃÕzÆÇÕÈÕqÕÕÕ5Õ_ÕpÕÍÕÍÕ{Ç{{{||ÈÈÈppp4__5577f9:;;;`<<m=>>>??@BBDDDEÖÖFHHÖÖHIIIJJJLLOÖNÖPPQPÖÖPRQPRQRRRÖÖTTÖXTÖÖX[X[X[][ÖÖ]Y]ÖÖ]]]ÖÖ]]]]]Y]]]ÖYÖXÖ[XTXTTVRVRRRÖÖRRÖPÖPPPPoKKLLKLLÖÖJJÖcÖHFEDEbbDDBÖBÖÖÖ@Ö?Ö>==n<<g<;Õ;;;Õ:Õ7Õ_s4ppÈpÑÈÕÈÈÕÕ|ÇÕ}Õz~yyÀÁÁÂxÂxÔwÔwÜÛÚvvÛ",
        "ÙÚÎáÛÛÚvÓwwwwÔxÂÁÀÃ~zÌ{{ÍÈpp44ppÈÈÍ|É{{{ÇÇ{ÍÍÍÈÈÈpp4s_577ff8:::;<<n====>>>??@BBDDEEFcFHIHIIJHcJJJJKKKPPPPPPQPPPPQRRRRUUTTTTX[XYXY[YYX]]]]]Y]]]]]]]]]]]]]][YYYY[YX[XTTTVVUWRRRRRRRPPPPooKKKJJLJLJJIHHiFFEEDDDhhBBBB@@@?>>=>nnnn<;:;;;98f777_q4pppÈÍÍÍÍÍÍÉ{{}ÌÆ~~yyÀÀÁÂÂx×xÔwwwÜÛÚvvÛ",
        "ÙÚÎáÛÛÚÓwwwÔÔÔxÂÂÁyy~zÆ}Ç{ÉÍÈ|ÍÍ|{{{Ç{{ÇÇÇ{ÍÍÍÈppp44__55778::;;;<<`l==>>>>@@@BDBbEEEFFFHHHHJHiIJJJKKoooPoPPPPPQRQRRRRRTTTTTTXT[YYX]YYY]]]]]]]]]]]]k]]]]]]]]]]][YXXXTTWTUTRRRQRQPPPPPOjKKJJLKJJJJJiiHHFFEEDDBBBBBB@@@?>>>>g`;<;;;:9ff:f877s4pÈÈÈÍ|{ÍÉØ{{ÇÇÌÌÆz~~ËyÀÁÁÂ×xÔÔÔÔwwÜÛÚávÙ",
        "ÙÚÎÎÛÛÛÛÜÜÜÜââââãããäääåææuuÝuÝÝuuuuuuuÝuuÝÝÞÞáávvvvvÓwÓwwÔwwÔxxxxÂxÂÂÂÁÁÁÀÀÀÀËËËy~~~~~~zzzzzzzzzÆzzzÆÌÌÌÌ}}}}ÇÇÇÇÇÇÇ{{Ç{{{{|ÉÍ|Í|ÍÍÈÈÈÈÈÈÈÈÈÈÈÈÈÈÈÈÈÈÈÍÍÈÈÍÍÍ||Í|Í{Ç{{Ç{ÇÇÇÇÇÇÇÇ}}}Ì}ÌÆÌÆÆÆzzzzzzzzzÄ~~~ËËËËËÃÃÃÀÀÀÀÁÁÂÂÂÂxxxxÔÔÔÔwwÓwÓÓvvváÎÎÝÝÝÝuuuuuuæuæååääääãããâââââÜÜÜÜÜÛÚááÙ",
        "ÙÚááÛÛÛÛÜÜÜÜâââââãäääääååçææuuuuuuuuuuuuuÝÝÎÎááávvvvÓwwwwwÔÔxÔxxxxxÂÂÁÁÁÁÀÊÀÃÃËËËËËË~ÄÄÄ~~zzzzzzzÆÆÆÌÌÌÌÌ}ÇÇÇÇÇÇÇÇ{ÇÇ{{{{{|||ÍÍÉ|ÍÍÍÉÍÈÈÍÍÈÈÈÈÈÈÈÈÈÍÈÉÈÈÍÈÍÍÍÉ|Í{{{{ÇÇ{{ÇÇÇÇÇÇÇÇ}}}}ÌÌÌÆÆÆzzzzzzzzzÄÄ~~yyËÃÃÃËËÃÁÀÀÊÁÁÂÂÂxxxxÔwÔwwwwwÓÓvvvváÎÎÎÝuuuuuuææèæååääääãããâââââââÜÜÜÛÛÚvÎÙ",
        "ÙÚáávÚÚÚÚééééééééééééééééêêêêêêêêêêêêêêêêêêêêêêêêêêê6666666666666666AAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGMMMMMMSSSSSSSSSeeSeeeeeZeZZZZZ^^Z^^^^^^^^^^^^^^^^^ZZ^Z^ZZZZZZeeeeeSSSSSSSSMMMMMMMMMGGGGGGGGGGGGGGAAAAAAAAAAAAAA6A66666666666666666êêêêêêêêêêêêêêêêêêêêéééééééééééééééééÚÚÚÚÚváÙ",
        "ÙÚávvvÏÓwwwÔx×xÂÂÁÁÁÃÃyy~~zzzÆÌÌ}}Ì}}}Ç{{{ÉÉÈÈÈpprq_557tf9::;;;<`gn=>>>>a@?@@BBBCDDDEFFFHFHJJJJLJLKKKjPKPPQPQQQQRRRVRTVVTXX[X[XYY]Y]YY][]]]]]]]]]]]Y]Y]]YYYYYXXXTXTTTTVRRRRRQQPPPPPPKLLLJJJJHiHFFEFEbbDDBBB@@@@a>>>==lg<;;:::997755__44pÈÈÍ{{{{Ç}}ÌÌÆzÆÅ~~~~ËËÒÀÁÁÂÂÂxÔÔÔwwwÏvvááÎÙ",
        "ÙÚáávvÓwwwÔÔxxxÂÂÂÁÁÒËy~~~~ÅÅÆzzÌÌÌÌ}{{{{ÉÍÍÈÈp4p445_77799:::<<<gm===>>a??@BB@BDDhEEEEFFHHHiIJJJLLLKKKOPPPPPQQRQRRWRTRWWTTXXXYXXYYX]][]]]]]Y]]]]]]]]]]]]k]YYYY[XTTTTRWTWRQRQQQPQPPjKLKKLJJJciIHFFFFEEDhBBBBB@@?>>>>=nn<<<:::89f7552_rpppÈÍ|{{{Ç}Ì}ÆÆzzzzÄÄyÃÃËÊÀÁÂÂÂxxÔÔwwÓwvvvááÎÙ",
    ]

    static let colors: [Character: NSColor] = [
        "!": NSColor(hex: 0x9DA6BA),
        "#": NSColor(hex: 0x798996),
        "$": NSColor(hex: 0x000000),
        "%": NSColor(hex: 0xF8FEFF),
        "&": NSColor(hex: 0x415360),
        "'": NSColor(hex: 0xB0C3CD),
        "(": NSColor(hex: 0x687082),
        ")": NSColor(hex: 0x3A4858),
        "*": NSColor(hex: 0x23293C),
        "+": NSColor(hex: 0x124B06),
        ",": NSColor(hex: 0xCCD5EF),
        "-": NSColor(hex: 0x09090E),
        ".": NSColor(hex: 0x516871),
        "/": NSColor(hex: 0x68798A),
        "0": NSColor(hex: 0x9EAFBA),
        "1": NSColor(hex: 0x1CD304),
        "2": NSColor(hex: 0x1F1E33),
        "3": NSColor(hex: 0xD5E0E4),
        "4": NSColor(hex: 0x201E32),
        "5": NSColor(hex: 0x201F33),
        "6": NSColor(hex: 0x59586B),
        "7": NSColor(hex: 0x211F33),
        "8": NSColor(hex: 0x202034),
        "9": NSColor(hex: 0x211F34),
        ":": NSColor(hex: 0x212035),
        ";": NSColor(hex: 0x222136),
        "<": NSColor(hex: 0x232137),
        "=": NSColor(hex: 0x232238),
        ">": NSColor(hex: 0x232239),
        "?": NSColor(hex: 0x23223A),
        "@": NSColor(hex: 0x24233A),
        "A": NSColor(hex: 0x5C5B6F),
        "B": NSColor(hex: 0x25243C),
        "C": NSColor(hex: 0x25253C),
        "D": NSColor(hex: 0x25243D),
        "E": NSColor(hex: 0x26253E),
        "F": NSColor(hex: 0x26253F),
        "G": NSColor(hex: 0x5E5D73),
        "H": NSColor(hex: 0x272540),
        "I": NSColor(hex: 0x272640),
        "J": NSColor(hex: 0x272641),
        "K": NSColor(hex: 0x282742),
        "L": NSColor(hex: 0x292741),
        "M": NSColor(hex: 0x605F75),
        "N": NSColor(hex: 0x282842),
        "O": NSColor(hex: 0x292842),
        "P": NSColor(hex: 0x292843),
        "Q": NSColor(hex: 0x2A2844),
        "R": NSColor(hex: 0x2A2845),
        "S": NSColor(hex: 0x605F77),
        "T": NSColor(hex: 0x2A2946),
        "U": NSColor(hex: 0x2A2945),
        "V": NSColor(hex: 0x2A2846),
        "W": NSColor(hex: 0x292846),
        "X": NSColor(hex: 0x2A2947),
        "Y": NSColor(hex: 0x2B2A47),
        "Z": NSColor(hex: 0x616078),
        "[": NSColor(hex: 0x2B2947),
        "]": NSColor(hex: 0x2B2A48),
        "^": NSColor(hex: 0x626179),
        "_": NSColor(hex: 0x201E33),
        "`": NSColor(hex: 0x222237),
        "a": NSColor(hex: 0x242239),
        "b": NSColor(hex: 0x25253D),
        "c": NSColor(hex: 0x262540),
        "d": NSColor(hex: 0x282841),
        "e": NSColor(hex: 0x615F77),
        "f": NSColor(hex: 0x201F34),
        "g": NSColor(hex: 0x232237),
        "h": NSColor(hex: 0x26253C),
        "i": NSColor(hex: 0x262640),
        "j": NSColor(hex: 0x292742),
        "k": NSColor(hex: 0x2A2948),
        "l": NSColor(hex: 0x222238),
        "m": NSColor(hex: 0x232138),
        "n": NSColor(hex: 0x222138),
        "o": NSColor(hex: 0x282744),
        "p": NSColor(hex: 0x1F1E31),
        "q": NSColor(hex: 0x201F32),
        "r": NSColor(hex: 0x1F1F32),
        "s": NSColor(hex: 0x1F1F33),
        "t": NSColor(hex: 0x202033),
        "u": NSColor(hex: 0x151420),
        "v": NSColor(hex: 0x161622),
        "w": NSColor(hex: 0x171623),
        "x": NSColor(hex: 0x181725),
        "y": NSColor(hex: 0x1A1A29),
        "z": NSColor(hex: 0x1B1A2B),
        "{": NSColor(hex: 0x1D1C2E),
        "|": NSColor(hex: 0x1D1C2F),
        "}": NSColor(hex: 0x1C1C2D),
        "~": NSColor(hex: 0x1B1A2A),
        "À": NSColor(hex: 0x1A1827),
        "Á": NSColor(hex: 0x191827),
        "Â": NSColor(hex: 0x181826),
        "Ã": NSColor(hex: 0x1A1928),
        "Ä": NSColor(hex: 0x1A1A2A),
        "Å": NSColor(hex: 0x1C1B2B),
        "Æ": NSColor(hex: 0x1C1B2C),
        "Ç": NSColor(hex: 0x1C1B2E),
        "È": NSColor(hex: 0x1E1D30),
        "É": NSColor(hex: 0x1D1D2F),
        "Ê": NSColor(hex: 0x191927),
        "Ë": NSColor(hex: 0x1A1829),
        "Ì": NSColor(hex: 0x1C1B2D),
        "Í": NSColor(hex: 0x1E1C2F),
        "Î": NSColor(hex: 0x161520),
        "Ï": NSColor(hex: 0x171622),
        "Ð": NSColor(hex: 0xC9990E),
        "Ñ": NSColor(hex: 0x1F1E30),
        "Ò": NSColor(hex: 0x191828),
        "Ó": NSColor(hex: 0x161623),
        "Ô": NSColor(hex: 0x171724),
        "Õ": NSColor(hex: 0xCACAD0),
        "Ö": NSColor(hex: 0xCECED5),
        "×": NSColor(hex: 0x171825),
        "Ø": NSColor(hex: 0x1E1D2E),
        "Ù": NSColor(hex: 0x100F17),
        "Ú": NSColor(hex: 0x4D4C57),
        "Û": NSColor(hex: 0x101017),
        "Ü": NSColor(hex: 0x111119),
        "Ý": NSColor(hex: 0x161420),
        "Þ": NSColor(hex: 0x151520),
        "ß": NSColor(hex: 0x292841),
        "à": NSColor(hex: 0x1C1C2E),
        "á": NSColor(hex: 0x161521),
        "â": NSColor(hex: 0x11111A),
        "ã": NSColor(hex: 0x12121B),
        "ä": NSColor(hex: 0x13121C),
        "å": NSColor(hex: 0x13131D),
        "æ": NSColor(hex: 0x14131E),
        "ç": NSColor(hex: 0x13131E),
        "è": NSColor(hex: 0x14131D),
        "é": NSColor(hex: 0x51515E),
        "ê": NSColor(hex: 0x555465),
    ]
}