// Wamp/Skinning/ClassicSprites/ClassicEQSheets.swift
// GENERATED pixel maps extracted 1:1 from base-2.91 sprite sheets
// (scripts in the session scratchpad; re-extract from skins/base-2.91.wsz).
// Baked text and LED art are not worth re-deriving as vector structure —
// exact pixel maps drawn as 1-pt rects stay crisp at every backing scale.

import AppKit

enum ClassicEQSheets {
    static let eqGraphBg = [
        "!#$%%&&'(()***$++,,,,,-.../0001223343456677888899:;<=>>>>????@ABCDCEBFBBBGHIFGIGIJJJJJKJGJJJJJJJJJKJJJFIIJGGFFHBB",
        "LL$#%'&'(())*M$+,+,,,NN.../0022O2333445666P888:89<;>9=>>??>??@AEECDBBBFFIFHGGFJJGGGJJJKJJJJJJJJJJGKGJGGFGIFFFBHDB",
        "LL$%%''(())**M$++,,,,,N.../002222334445767888889Q9;=>>>>?>??@?AEBDBBBBFFFIHJGFFIGJGGGJKJJJJJJJJJJJKJJJFGFGFBGFRBB",
        "##$SSS(())***T$+,+,,,-...0/0U0222344P456V6888889:W;>>>>?>???@@R@DEDBBBFGFGKFJIJJIJXJJJKJJJJJJJJJJJKJJFJJFFFFBBRBB",
        "L%$%SS'(((**Y+$++,,,N-...0/202233334465PP788889:9W;>>>>>?>@?@@ACEDBBBBBFFGHIJJJJJJJJJJKJJJJJJJGJJJHGJFFJFGIBFBABB",
        "##$S''(())**ZZ$++,,,,.-..0/0OO2333446V5V888:8:9<:9;>>>>>?@??@@ACBBBBFFGIIGHJJJJJJIJJJJKJJJJJJJJJJGKJIGJGFBGFBFRBD",
        "%%$'&'(()[**M[$,+,,N,..000/022223444465P7888:::QWW;>>>?>?@?@@@RD@BBFFBBBGGKGGIIGJIJJJJKJJJJJJJGJJJHJJJGIFGBBBBADC",
        "##$'((()))**++$,,,,N-..000/02222444646588888:999=>;>>>>????@@@AEBBBBBBGBFXHGFJJGJJJJJGKJJJJJJJJJGGKJGGGFFFFBBBABB",
        "%%$S'(((****++/,,,,-..0000/0223334446V568888:::<W];>>>???@@@C@R@CBBBFBGFGGKJGJIJJJJJJJKJJJJJJJJJJGKJGIGFFGFBBBRBB",
        "#%$''(())MTT++$,,,,,...000/0223334666658888:8:W9<];>>>>??@@@DEACEBFBBFFIGXHGGJJJJGJJJJKJJJJJJJJJJJKIXGJFBFBFDEABE",
        "#S$&((())*T+++/+,,,-...000/0223344666P58888:8W9WW>;>>>>@@?@@@@AEBBBBGFGIGFKXXGJGXJGJJJKJJJJJJJJGGGKGIJGIFBBBFBRBC",
        "%S$S((()**Y+++/,,,N...0002/O333434466658888::999W>;>>????@@CE@AEBBFFFIGFFFKGGJJJGJJJJJKJJJJJJIGJGJKJGGIIIBFDBDREE",
        "SS$'()))*T[Y++/,,-N...0000/233344467VV58888:99W=>>;>?>>?@@@E@CABBBBIFFGFFIKGJJJJJGGJJJKJJJJJJJJGGJKGIFIGFBBBB@REB",
        "%'$')()**+Y++,/,,N-.0.0000/323434666765888:8:9<W>>;>???@@@@@@@ABDBFFFBFGGJKGJJJJJJJJGJKJJJJJGJJJGXHGGIFFFFBBDBA@E",
        "S&$(())**Y++,+/,N-..00002O/23444446676588:::<W]9<>;>?>??@C@C@ERBBBBBBIFFFXKGGJJJJJJJJJKJJJJJJJGJGJHIFGGFFBBBBBA@@",
        "&($()()**M+++,/,-.-.00002O/O33444777P85888899W=>>>;?????@@E@CEABBBBFBGFGFJKIGJIJIJJJJJKJJJJJJGJJJJKIGFBGFBBBBCRC@",
        "''$))(**YY++,,/---.0.000O2/233444768P85::::99W9>>>;??>@@@@@DBBRBBBFBFIGGGFKFXJJJJJJJJJKJJJJJJXGGFFKFFIFFFDBBBBR@@",
        "S'$)))*[ZY+,,,/-NN...00122/2344446686858::99<=>>>>A?>@@?@@CCC@RFFBBFGIIGJGKJJJJGIGJJJJKJJJJGGGGJJGHFGGBBBFFBBCA@@",
        "'($()**Z+++,,,/-.-..0002O2533344467788588:99]<<>>>A???@@@@CB@ERBBFFIGFGGGGKJJJJJJJJJJJKJJJJJGGJIGGKGIFFFBDDBD@A@@",
    ]

    static let graphColors: [Character: NSColor] = [
        "!": NSColor(hex: 0x201E32),
        "#": NSColor(hex: 0x201F33),
        "$": NSColor(hex: 0x59586B),
        "%": NSColor(hex: 0x211F33),
        "&": NSColor(hex: 0x202034),
        "'": NSColor(hex: 0x211F34),
        "(": NSColor(hex: 0x212035),
        ")": NSColor(hex: 0x222136),
        "*": NSColor(hex: 0x232137),
        "+": NSColor(hex: 0x232238),
        ",": NSColor(hex: 0x232239),
        "-": NSColor(hex: 0x23223A),
        ".": NSColor(hex: 0x24233A),
        "/": NSColor(hex: 0x5C5B6F),
        "0": NSColor(hex: 0x25243C),
        "1": NSColor(hex: 0x25253C),
        "2": NSColor(hex: 0x25243D),
        "3": NSColor(hex: 0x26253E),
        "4": NSColor(hex: 0x26253F),
        "5": NSColor(hex: 0x5E5D73),
        "6": NSColor(hex: 0x272540),
        "7": NSColor(hex: 0x272640),
        "8": NSColor(hex: 0x272641),
        "9": NSColor(hex: 0x282742),
        ":": NSColor(hex: 0x292741),
        ";": NSColor(hex: 0x605F75),
        "<": NSColor(hex: 0x282842),
        "=": NSColor(hex: 0x292842),
        ">": NSColor(hex: 0x292843),
        "?": NSColor(hex: 0x2A2844),
        "@": NSColor(hex: 0x2A2845),
        "A": NSColor(hex: 0x605F77),
        "B": NSColor(hex: 0x2A2946),
        "C": NSColor(hex: 0x2A2945),
        "D": NSColor(hex: 0x2A2846),
        "E": NSColor(hex: 0x292846),
        "F": NSColor(hex: 0x2A2947),
        "G": NSColor(hex: 0x2B2A47),
        "H": NSColor(hex: 0x616078),
        "I": NSColor(hex: 0x2B2947),
        "J": NSColor(hex: 0x2B2A48),
        "K": NSColor(hex: 0x626179),
        "L": NSColor(hex: 0x201E33),
        "M": NSColor(hex: 0x222237),
        "N": NSColor(hex: 0x242239),
        "O": NSColor(hex: 0x25253D),
        "P": NSColor(hex: 0x262540),
        "Q": NSColor(hex: 0x282841),
        "R": NSColor(hex: 0x615F77),
        "S": NSColor(hex: 0x201F34),
        "T": NSColor(hex: 0x232237),
        "U": NSColor(hex: 0x26253C),
        "V": NSColor(hex: 0x262640),
        "W": NSColor(hex: 0x292742),
        "X": NSColor(hex: 0x2A2948),
        "Y": NSColor(hex: 0x222238),
        "Z": NSColor(hex: 0x232138),
        "[": NSColor(hex: 0x222138),
        "]": NSColor(hex: 0x282744),
    ]

    static let eqLadder = [
        "                                                                                                                      ",
        "    !           !           #           $           %           &           '           (           (           '     ",
        "    !           !           #           $           %           &           '           (           (           '     ",
        "    !           !           #           $           %           &           '           (           (           )     ",
        "    !           !           #           $           %           )           (           (           (           )     ",
        "    !           !           #           $           %           &           '           (           '           &     ",
        "    !           !           #           $           %           &           '           (           (           )     ",
        "    !           !           #           $           %           )           (           (           '           &     ",
        "    !           !           #           $           %           &           '           (           (           &     ",
        "    !           #           #           $           %           )           (           (           (           )     ",
        "  !!!!!!!!!!!!!#################$$$$$$$$$$$$$$$$%%%%%%%&&&&&&&)&&&&)')'''''''('((((((((((((((((((((((''((')''')&&&&   ",
        "    !           #           #           $           %           &           (           (           (           )     ",
        "    !           #           #           $           %           &           (           (           (           )     ",
        "    !           #           #           $           &           &           (           (           (           )     ",
    ]

    static let eqDbRowTop = [
        "                                                                          #           $           $           &           )           '           (           (           (           '                                                                       ",
        "                                                                                                                                                                                                                                                              ",
        "                                   **  **     * *                                                                                                                                                                                                             ",
        "                                *   *    *    * *                                                                                                                                                                                                             ",
        "  +++++              ++++++    ***  *  ***  *** ***        +++++,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,++++          ",
        "                                *   *  *    * * * *                                                                                                                                                                                                           ",
        "                                   *** ***  *** ***                                                                                                                                                                                                           ",
        "                                                                                                                                                                                                                                                              ",
        "                                                                                                                                                                                                                                                              ",
        "                                                                                                                                                                                                                                                              ",
    ]

    static let eqDbRowMid = [
        "                                                                                                                                                                                                                                                              ",
        "                                                                                                                                                                                                                                                              ",
        "                                      **     * *                                                                                                                                                                                                              ",
        "                                 *   *  *    * *                                                                                                                                                                                                              ",
        "  +,,,,              ,,,,++     ***  *  *  *** ***         ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,++          ",
        "                                 *   *  *  * * * *                                                                                                                                                                                                            ",
        "                                      **   *** ***                                                                                                                                                                                                            ",
        "                                                                                                                                                                                                                                                              ",
        "                                                                                                                                                                                                                                                              ",
        "                                                                                                                                                                                                                                                              ",
    ]

    static let eqDbRowBottom = [
        "                                                                                                                                                                                                                                                              ",
        "                                                                                                                                                                                                                                                              ",
        "                                   **  **     * *                                                                                                                                                                                                             ",
        "                                    *    *    * *                                                                                                                                                                                                             ",
        "  +++++              ++++++    ***  *  ***  *** ***        +,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,,,,,,           ,,+++++           +++++          ",
        "                                    *  *    * * * *                                                                                                                                                                                                           ",
        "                                   *** ***  *** ***                                                                                                                                                                                                           ",
        "                                                                                                                                                                                                                                                              ",
    ]

    static let eqLabelStrip = [
        " -    -                                                                           ,,   ,,          , ,,,  ,,         ,,  ,  ,,        ,,   ,,   ,,         , , ,            ,,  , ,            ,,  , ,          , ,,  , ,         ,   , , +         +  ++  + +                 -   ",
        " -    -           ++  ++  ,,,  +  + + ++                                         ,    ,  ,         ,   , ,  ,          , , ,  ,      ,    ,  , ,  ,        , , ,              , , ,           ,    , ,          ,   , , ,         ,  ++ + +         + +    + +                 -   ",
        " -    -           + + + + +   + + +++ + +                                        ,,,  ,  ,         ,  ,  ,  ,        ,,  , ,  ,      ,,,  ,  , ,  ,        , ,,             ,,  ,,            ,,,  ,,           ,   , ,,          + + + ++          + +++  ++                  -   ",
        " -    -           ++  ++  ++  +++ +++ ++                                         ,  , ,  ,         ,  ,  ,  ,          , , ,  ,      ,  , ,  , ,  ,        , ,,               , ,,            ,  , ,,           ,  ,  ,,          + +++ ++          + +  + ++                  -   ",
        " -    -           +   + + +   + + + + +                                          ,  , ,  ,         , ,   ,  ,          , , ,  ,      ,  , ,  , ,  ,        , , ,              , , ,           ,  , , ,          , ,   , ,         +   + + +         + +  + + +                 -   ",
        " -    -           +   + + +++ + + + + +                                           ,,   ,,          , ,    ,,         ,,  ,  ,,        ,,   ,,   ,,         , , ,            ,,  , ,            ,,  , ,          , ,,, , ,         +   + + +         +  ++  + +                 -   ",
        " -    -                                                                                                                                                                                                                                                                        -   ",
        " -    -                                                                                                                                                                                                                                                                        -   ",
        " -                                                                                                                                                                                                                                                                             -   ",
        " -                                                                                                                                                                                                                                                                             -   ",
        " -   ----................///////////////////////////!!!!!!!!!!!!!!!!################$$$$$$$$$$$$$$$$%%%%%%&&&&&&&&&))&)))))')'''''(('(((((((((((((((((''('('''''')))))&&&&&&&&%%%%%%%%%$$$$$$$$$$$$$$##############!#!!!!!!!!!!!!!!!!!////////////////////.................-----   ",
        " -                                                                                                                                                                                                                                                                                 ",
        " -                                                                                                                                                                                                                                                                                 ",
    ]

    static let colors: [Character: NSColor] = [
        "!": NSColor(hex: 0x59586B),
        "#": NSColor(hex: 0x5C5B6F),
        "$": NSColor(hex: 0x5E5D73),
        "%": NSColor(hex: 0x605F75),
        "&": NSColor(hex: 0x605F77),
        "'": NSColor(hex: 0x616078),
        "(": NSColor(hex: 0x626179),
        ")": NSColor(hex: 0x615F77),
        "*": NSColor(hex: 0xC9990E),
        "+": NSColor(hex: 0xCACAD0),
        ",": NSColor(hex: 0xCECED5),
        "-": NSColor(hex: 0x4D4C57),
        ".": NSColor(hex: 0x51515E),
        "/": NSColor(hex: 0x555465),
    ]
}